### ISSUE TITLE
Capacity graph tooltip dates do not match task dates

### ISSUE THREAD

**Issue by mawds** [UoMResearchIT/CapX#103]
The end date of a task does not always match the tooltip for the dates shown on the "Schedule" pane. Example screenshots for RTP-99 AI Foundry shown below.

Email correspondence with @aharwood2 explains that is is due to rounding to week blocks:

> This is an artifact of the capacity graph which averages work out into weekly blocks using Mondays as the dividing point. This is to ensure the resolution of a block on the capacity graph was something sensible but I perhaps need a rethink on how this feature works since inevitably, this is going to catch people out since what you end up with is the block on the capacity graph extending from the nearest Monday before the assignment starts to the nearest Monday after. In this case for Adina, she start on Monday 22nd August so that will show correctly as the shaded block will start on the same day, but since AIF finished on Friday 30thJune, the shaded block extends two extra days up to midnight on Monday 3rd July which is what appears in the tooltip.

![image](https://user-images.githubusercontent.com/12030124/237028722-570094a9-7fcb-4362-badf-21f20703e3a0.png)
![image](https://user-images.githubusercontent.com/12030124/237028745-09b3d2ce-fe32-47ad-b3de-0e2ad52b979c.png)

**Comment by aharwood2** [comment]
Turns out there is more to this that I thought. The interval divider is not always a Monday but is a 7-day multiple of the start date of the earliest task that person is assigned to which is even worse! Should be easy enough to make it so that the marching window is self-adjusting so I'll give it a go.

**Comment by aharwood2** [comment]
Another thing this throws up is whether the end date is considered a day of work for the task or not. So a task which has its start date of a Monday then its end date of the following Monday, we so far seem to assume that the task is worked on for 7 days i.e. Monday to Monday but excluding the end date. This is all kinds of confusing so I'm going to have to look at this too!

**Comment by aharwood2** [comment]
The quick fix for the date mismatch is just to adjust the time marching resolution to a day. It will take 7 times as long to process the chart data but at least the dates will line up properly.

**Comment by aharwood2** [comment]
I believe this is fixed now although tasks may need to be edited and then re-saved in order for it to take effect.
