### ISSUE TITLE
Add additional cancelled project statuses - lack of funding & lack of RSE resource

### ISSUE THREAD

**Issue by cjfullerton** [UoMResearchIT/CapX#107]
It would be useful to be able to differentiate between projects that were cancelled due to the funding not being rewarded and those cancelled due to us not being able to resource them with RSEs.

**Comment by aharwood2** [comment]
Perhaps we even need 3 here: Funding Failure, Cancelled by Customer (i.e. they went elsewhere), Unable to Service (lack of resource etc.)

**Comment by aharwood2** [comment]
Done -- added three states and a couple of extension methods to the enum class to make it easier to query across all the different cancelled and finished states.
