### ISSUE TITLE
Resource Allocation not working when more than one edited

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#112]
When editing or adding new people as resources on a task, only the first changed is saved and all the rest are ignored.

**Comment by TheresaTeng** [comment]
What I noticed:
When adding a new task, and assigning it to two people with different percentage, the last % number will overwrite the first one.

**Comment by aharwood2** [comment]
OK, I've got to the bottom of this. It was doing a check against the entity ID which of course is zero when adding a new entity that has not yet been saved to the DB so when adding two new entities they both have the same entity ID.
