### ISSUE TITLE
Include portfolio manager info in project

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#115]
It would be useful to include portfolio manager's info in a project, so we can easily check with the manager if needed. It wasn't a problem when the projects were grouped by Faculties + MDS + WADS, but it's not the case now.

**Comment by aharwood2** [comment]
I guess I'm trying to avoid too much duplicate information between CapX and RTP. Technically, if you have the RTP code from CapX you can easily look it up on RTP to see who owns it. I'm actually tempted to remove the portfolio option from CapX as these are out of sync somewhat now. Will think about it.

**Comment by aharwood2** [comment]
I will do this I think as it will be useful to filter the capacity view on projects a certain manager owns I think.

**Comment by aharwood2** [comment]
Added this in the latest build. The DB needs an update as by default the PM will be unset. Needs to be populated to work properly with "view capacity by PM" feature.
