### ISSUE TITLE
Edit skill tag list

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#116]
Can we have function to edit skill tags? 

Can more skills be added in?
Here are a few things mentioned at one of my i-to-1s: C++, HPC, Shell Scripting, Dev-Ops

**Comment by aharwood2** [comment]
I can't remember how this is done now. I think there is already a way to do this. I think you have to edit a person and then there is a "tag manager" option top right?

**Comment by TheresaTeng** [comment]
Just had a look in People page, but no tag manager. There is an Edit button but that's for editing a person's availability.

**Comment by aharwood2** [comment]
Here it is:
<img width="1419" alt="Screenshot 2023-08-17 at 12 35 16" src="https://github.com/UoMResearchIT/CapX/assets/8614261/11430e98-41fa-41ce-8ad5-f1ce2251d9e6">
(Click on Tags top right) then you get:
<img width="1419" alt="Screenshot 2023-08-17 at 12 35 32" src="https://github.com/UoMResearchIT/CapX/assets/8614261/a570ab09-f555-4b36-81fc-00531ce61462">
