### ISSUE TITLE
Add RLP innate codes

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#121]
It would be useful if the RLP Innate codes were added to the 'Innate Activity' drop-down box when editing a project, because we do have some work on RLP projects. Or perhaps just have a bucket option in the list of 'RLP'.

Admittedly it is not always obvious which ones the RLP codes are as they don't have consistent naming or coding, which might be a problem (unless we ask Kamie to do something about that).

Examples codes we done work on recently are: P00658, P00671, P00711, P00770.

**Comment by aharwood2** [comment]
If you can provide me with the codes then I'll make sure they are in the next update.

**Comment by ajerrison-manchester** [comment]
P00658 Digital Image Viewer (used in project RTP-107)
P00671 Research Networking and Collaboration (used in project RTP-159)
P00711 Enhancing support for research (used in project RTP-17)
P00770 Research lifecycle project G (used in project RTP-15)

There are quite a lot of  other RLP codes too which I guess might need some work occasionally:

P00772 - Research Lifecycle project L
P00695 - Research Lifecycle project C
P00850 - Grant management system
P00673 - Research lifecycle project N1
P00670 - Developing Research Support Professions

**Comment by aharwood2** [comment]
OK, I might just pull the full active list from Innate and dump that into the app. I wish it had an API to do this query but never mind.

**Comment by aharwood2** [comment]
Done. Changed the lookup so that the source file is now on Firebase and the app pulls the source data from there. We can then update independently. Added all active codes to the list now. Will be in next release.
