### ISSUE TITLE
Saving allocated time when adding a task bug

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#124]
When editing a task on a project you can allocate an RSE at a particular FTE. When updating the allocation percentage the edit mode displays a tick button to confirm the amount and a cross button to cancel edit mode. 

However there is a bug when cancelling the edit mod; to replicate:

- press the edit button against an entry for the RSE's allocation
- change the %FTE number (do not press the confirm button)
- press cancel 
- The record is saved with the new value.

Expected: When cancel is pressed the record would not be saved and the display would revert to the previous value.

**Comment by aharwood2** [comment]
Just replicated this and it is actually just a wider issue of the case where any of the elements on the row being edited are changed. I'll take a look now.

**Comment by aharwood2** [comment]
Fixed in next release.
