### ISSUE TITLE
Style issues related to RadzenDataGrid and MainLayout

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#126]
When RadzenDataGrid is used in a "content" div, and a "top-row" div is there too, this issue will occur:

If the page size in a RadzenDataGrid is big and use needs to scroll down to see the bottom rows, the RadzenDataGrid's column header will cover the page header.
If there are frozen columns, these columns will remain covering page header, but the page header will reappear over the other not-frozen columns.

To fix it, add z-index for class "top-row" in "MainLayout.razor.css". Note "top-row" is in two places.

**Comment by aharwood2** [comment]
Thanks Theresa -- I found that I had to make this a pretty high number for all the components to be beneath it. I guess it is going to depend on how many components are drawn on the page. I picked 20 for now and it seems to work for the data grid and the charts.

**Comment by aharwood2** [comment]
Fixed in next release.
