### ISSUE TITLE
Style issue in RadzenDataGrid  for column resizing

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#127]
RadzenDataGrid has a feature to allow user to resize a column. However user can reduce a column's size to 0 and it can be confusing. To avoid it they introduced a new attribute "MinWidth". It would be better to use this for a column if you want to keep the column resizing enabled.

**Comment by aharwood2** [comment]
Reported here: https://forum.radzen.com/t/radzendatagrid-column-resize-minimum-width/8979

There is a MinWidth property for the component but will have to add maually for every column unless I can find a way for it to be picked up via CSS but not sure if the local property will override it when rendered.

**Comment by aharwood2** [comment]
Was addressed by a PR here: https://github.com/radzenhq/radzen-blazor/commit/c6ce339d40ad4474f069feb6e5a33524b18fd8f3 and it isn't overriden if not set so I answered my own question!

**Comment by aharwood2** [comment]
I've just added a `MinWidth` property to every `RadzenDataGridColumn` that isn't `Resizable=false`. Will be fixed in the next version.
