### ISSUE TITLE
Clicking on a task bar on the schedule plot on a project page opens that task for editing. 

### ISSUE THREAD

**Issue by cjfullerton** [UoMResearchIT/CapX#130]
This would make assigning RSEs to complicated multi-task projects (e.g. RTP-135) much easier.

**Comment by aharwood2** [comment]
Can do this pretty quickly so will get it in the next release.

**Comment by aharwood2** [comment]
Done. Will be in the next release. I also took the liberty of adding a similar function that when you click on an individual's bar on the "All Team" capacity graph it automatically filters by that person.
