### ISSUE TITLE
Selecting multiple RSEs in capacity view who are assigned to tasks on the same project: task bars are amalgamated

### ISSUE THREAD

**Issue by cjfullerton** [UoMResearchIT/CapX#131]
I've raised this as I'm not sure it's behaving as intended.

When I select two RSEs who are assigned to the same project in the capacity view (for example Abby Gavin and Jonathon Taylor, assigned to RTP-135), the task bars for that project are combined together in a confusing way. 

![Screenshot 2023-11-10 at 17 03 27](https://github.com/UoMResearchIT/CapX/assets/3920981/695ad7bf-ccca-4306-99a3-4c613048c9d6)

The bottom RTP-135 bar shows an assignment of 80%. I was expecting two separate 40% bars.

**Comment by aharwood2** [comment]
This is actually intended in terms of how I understood the original requirement for #92 . However, I can also see how it would be useful to see them broken down individually. I can investigate how easy / difficult it would be to do this for the next release. I guess we would need to adjust the tooltip or the vertical axis label to indicate which person the bar belongs to? We would also need multiple total rows, one for each individual and then maybe a sum at the end?

**Comment by aharwood2** [comment]
Fixed in the next version. People now have their own total rows and there is also a summed total row at the end which I think is more useful?
