### ISSUE TITLE
Ability to edit/modify/split availability changes for an RSE

### ISSUE THREAD

**Issue by cjfullerton** [UoMResearchIT/CapX#136]
Currently the only option is to delete an availability change and then add a new one. Being able to edit existing availability changes would speed things up.

**Comment by aharwood2** [comment]
Sure -- not too difficult to do given we already use this design elsewhere.

**Comment by aharwood2** [comment]
I've started to make the changes to this but I've come unstuck as the class hierarchy I've been using for this assumes that you have a separate service to manage entities of a particular type. Availability changes are part of the person model and are usually managed by managing the Person entity, hence indirectly. I'll probably have to either refactor to create a person service or do some manual work rathe than using the class hierarchy as it is designed. Will leave as WIP for now.

**Comment by aharwood2** [comment]
Fixed this up now and will be in the next release.
