### ISSUE TITLE
Make all FTE relative to 1.0 not 0.84

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#137]
Especially for @PhilBradbury even though he doesn't use the system as I know he didn't sleep well last night worrying about this.

As the models in the DB store their data WRT to the FTE post-non-working days everything was configured to use 0.84 as the base full time equivalent. This is obviously arduous with us having to convert into this unit all the time when inputting and outputting. This issue to track the refactoring of this back to a base unit of 1.0. A fair bit of work to do in different areas but best done now rather than later:

- [x] Update capacity page code and helpers and chart generation delegates
- [x] Update person and availability change pages code and helpers
- [x] Update resource input to use 0.X FTE instead of X% so it is consistent
- [x] Update tooltips which dynamically convert
- [x] Update the GaDMO export feature which also dynamically converts
- [x] Add a DB migration to update the resource table
- [x] Add a DB migration to update the availability changes table
- [x] Add DB migration to update the person table
- [x] Update Wiki to reflect these changes

**Comment by aharwood2** [comment]
All done! Seems to work alright but I'm sure stress testing it will break it somewhere. Will be in v1.7.0.

**Comment by PhilBradbury** [comment]
Ooooh, exciting times. Hope this didn't give you too many nightmares, and sorry for suggesting it as I don't even really use the tool! 🤣
