### ISSUE TITLE
Use substring search in "people/name" filter

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#139]
At the moment, if I search for "Hinder" in the People/Name filter, it says "No records to display".  It appears to work if I search for "Ian", so it's probably using a prefix search.  A substring search would probably be more useful.

![image](https://github.com/UoMResearchIT/CapX/assets/213274/90edc530-1f2c-40eb-8cb7-0f161c3110e8)
![image](https://github.com/UoMResearchIT/CapX/assets/213274/fac8e65e-5714-40c8-9bd4-c599df1c0f9b)

**Comment by aharwood2** [comment]
Fixed on branch v1.7. Will be in next release.
