### ISSUE TITLE
Access projects by RTP code

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#144]
It would be useful to be able to access project pages by a URL with the RTP code, rather than the current numbering, which is different. I assume the current number is a database index key or something.

At the moment, the URL for RTP-86 is

https://balex.itservices.manchester.ac.uk/projectdetails/24

where it would be nicer to be

https://balex.itservices.manchester.ac.uk/projectdetails/RTP-86

One could support both for backward compatibility, if that were needed.

The internal implementation detail of the database key is probably not something that should be exposed to the user, when we already have a unique ID for the projects which is user-visible.  This would also help when I want to refer to a project page in CapX; I can compose it without having to go to CapX itself.  It is also distracting to have this additional number visible.

Low priority, of course.

**Comment by aharwood2** [comment]
Ok, yes this would be useful. This is an easy one to do too, so can stick this in the next release.

I'm not sure backward compatibility is necessary as I'm not aware of anything that uses the CapX URLs.

I don't think you would find many normal users of web applications who would find a primary key in a URL to be distracting. I think I find SharePoint or SAML URLs more distracting than that! 😄

**Comment by aharwood2** [comment]
I wonder whether we can setup some kind of bi-directional hyperlink between RTP and CapX so you can easily access the relevant parts of each system. I guess we can add this to CapX easy enough but I'll have to look to see if Jira can be modified to add a button that heads over to CapX. Probably a separate feature but would be useful I think.

**Comment by ianhinder** [comment]
Maybe related: [here](https://community.atlassian.com/t5/Jira-Software-questions/How-can-I-have-a-custom-field-display-a-URL-from-Aha-and-have/qaq-p/1767238).

So you can add a "short text" field to the issue schema and manually enter the URL. If it's a URL, it gets turned into a link.  Whether this can be automated or templated is a different question, though, as well as whether it can be made more prominent than just another piece of metadata.  At that point you may as well just write the URL into the description field.

**Comment by aharwood2** [comment]
I've decided to do this using a query string. The next release you'll be able to access project details via their RTP as: https://localhost:5001/projectDetails?rtp=14

**Comment by aharwood2** [comment]
Further to this I've now added a custom field and an automation rule to Jira to auto-generate a suitable CapX URL to allow navigation directly from the demand card to the project details page. It is currently set to run if the CapX Link field is empty and the issue is updated so all existing projects should have this updated in future. Obviously they won't go anywhere until CapX is updated but doesn't matter.
