### ISSUE TITLE
Inconsistent end dates

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#145]
For RTP-145, if I go to https://balex.itservices.manchester.ac.uk/projectdetails/125, it says "end date" of 01-05-2024. There is one task in this project, with an end date of 01-05-2024.  However, if I go to the Capacity page and select AG, who is assigned to this task, the end of the assignment is given in the tooltip as 02-May-2024.

According to the [docs](https://github.com/UoMResearchIT/CapX/wiki/Projects), 
> End Dates
>
> Task end dates are included in the assignable duration. So if you have a fixed duration task that starts on Monday 2nd January 2023 and runs for 7 days duration, the end date will show as Sunday 8th January 2023 (technically 6 days later) not 7 days later. 

My guess is that the last day of work is 01-05-2024, and the tooltip is wrong/inconsistent, but I'm not sure about that.

Overall, I prefer to work with inclusive/exclusive ranges like in Python, i.e. closed-open intervals [start,end), as they allow you to express zero size intervals, but that is a technical issue, and people tend to think in terms of [start,end], especially when it comes to days, so I understand why this has been done.

**Comment by aharwood2** [comment]
I'll have a think about this as I can see the inconsistency being annoying but the inclusive end date makes the boxing of data for the charts make sense. A change of the tooltip would be easier but I don't want it to confuse people. We could just say that the CapX convention is inclusive end dates, full stop.

**Comment by aharwood2** [comment]
I've updated the tooltip so it just subtracts a day. The tooltip in the "Schedule" on the "Project Details" page now agrees with the "Capacity" chart so they are consistent. End dates remain inclusive. Fixed in commit https://github.com/UoMResearchIT/CapX/commit/056ba1405b715f406ea75bc6200e5bea7a817bcd
