### ISSUE TITLE
Absence Notification System

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#148]
I wonder if we can add a mechanism by which managers can report a member of staff off sick and have a page where we can easily see who is off? We might be able to tie this in with an email notification system which just fires off emails to anyone assigned to a project (if PM is sick) or any PM (if an RSE is sick). Seems like it would be more slick as a process?

**Comment by ianhinder** [comment]
Is there a privacy aspect to this?  e.g. if people who have no reason to know about someone's sickness can see information about it?  Maybe something to check before going ahead.  Might be OK if you can see sickness info only about people whose projects you manage, as there is a legitimate need there.  Does CapX know who is managing projects?

I gather the intent here is for being able to see short-term sickness, as long-term sickness would already be recorded in the availability part.

This might be an unpopular feature, as it is another step that a staff manager needs to go through when someone is sick.  "Slick" would be to have it automatically fed from the P&OD system underlying MyView, but I don't even have to ask if that is going to be straightforward :).

The current system of "Oh, I'm sorry to hear you're sick. Please let your projects know." might be overall less work?

**Comment by aharwood2** [comment]
@ianhinder  to cover your questions:

> Is there a privacy aspect to this? e.g. if people who have no reason to know about someone's sickness can see information about it? Maybe something to check before going ahead. Might be OK if you can see sickness info only about people whose projects you manage, as there is a legitimate need there.

There will be no information about sickness -- just whether they are absent from work or not. In fact, it doesn't have to even by limited to sickness, any kind of absence really. It is at least as privacy-conscious as the current process for notifying other managers of sickness.

> Does CapX know who is managing projects?

Yes, CapX does know who PMs each project -- or at least it does if PMs remember to tell it :)

> I gather the intent here is for being able to see short-term sickness, as long-term sickness would already be recorded in the availability part.

The intent is to cut down the number of places information has to be reported and just have absence reported once by someone (LM or RSE depends on how we design it) and then the system knows who needs to know a person isn't in that day and lets people know automatically.

> This might be an unpopular feature, as it is another step that a staff manager needs to go through when someone is sick. "Slick" would be to have it automatically fed from the P&OD system underlying MyView, but I don't even have to ask if that is going to be straightforward :).

It is not "another step" it is a more automated, single replacement step for the current 7 step process in the current ops policy.

> The current system of "Oh, I'm sorry to hear you're sick. Please let your projects know." might be overall less work?

That's not the current system though is it? The current system to make sure the message gets where it needs to go involves the LM having to post the message in two separate Teams channels which may or may not get read by managers and shared on. Seemed like an obvious mechanism to automate this given that CapX can easily determine who in the department ought to know someone is absent from a service management point of view.

**Comment by aharwood2** [comment]
- [x] button on people grid to add /edit absence for that person
- [x] new add absence section to person page showing past absences and in-line add
- [x] add status messages to project cards so that tasks which have an absent resource that are running or will start in 7 days or less will generate a warning
- [x] add status message to person page to highlight that they are currently absent
- [x] refactor the task-level icon system so that uses the status message queue rather than manual condition checks
- [x] email the project manager if a new absence is created or end date added and it will affect their task (needs an email service; can probably SMTP email to user_id@manchester.ac.uk and it will get through).
