### ISSUE TITLE
Package DotNetExtensions not found

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#151]
I am trying to build CapX, with a view to importing the RSESkillsGraph data.

When I run
```
dotnet restore "PPMTool.csproj"
```
I get an error
```
 > [ppmtool build 4/6] RUN dotnet restore "PPMTool.csproj":                                    
1.063   Determining projects to restore...                                                     
33.00 /src/PPMTool.csproj : error NU1102: Unable to find package DotNetExtensions with version (>= 1.2.0)                                                                                     
33.00 /src/PPMTool.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 0.0.6 ]
33.30   Failed to restore /src/PPMTool.csproj (in 31.92 sec).
```
Indeed, searching nuget.org, I don't find a package called DotNetExtensions.  Removing DotNetExtensions from PPMTool.csproj allows me to restore the project, but then PPMTool/Enums/Extensions.cs complains that DotNetExtensions is not found. I can work around this by commenting out the "using" line, and removing the reference to `me.GetDescription()`.  Is a different package needed than DotNetExtensions, to get the GetDescription method injected for Enums?

**Comment by aharwood2** [comment]
`DotNetExtensions` is available via the NuGet feed. I can add the feed to a nuget config in the root.

**Comment by aharwood2** [comment]
On second thoughts, the feed is private so there is a need to set your PAT in your development environment. If you are using docker then you will have to expose that environment variable. However, if you are using your IDE (which again, I can't understand people who don't -- sorry) then you will be prompted for your PAT for the feed the first time you open the solution. I still think it is worth sticking it in a nuget config so I will do that.

**Comment by aharwood2** [comment]
Do you think we need an issue here or one in the RSE Skills Graph repo? Perhaps a migration script in the latter so we can do this again in the future?

**Comment by ianhinder** [comment]
I've added a nuget.config file for the feed in https://github.com/UoMResearchIT/CapX/tree/153-support-running-capx-in-docker as well as the necessary docker logic to add the authentication information to the source at build time from env vars.  Works for me!

The nuget.config commit is https://github.com/UoMResearchIT/CapX/commit/42f063050956e154a3ad14412b2194ab5888f996 if you want to cherry-pick it before the docker work is finished.

**Comment by ianhinder** [comment]
> Do you think we need an issue here or one in the RSE Skills Graph repo? Perhaps a migration script in the latter so we can do this again in the future?

I've created #155 in CapX, since it's an enhancement to CapX.

**Comment by aharwood2** [comment]
@ianhinder where are we at with this. Now you have added the nuget config this can be closed?

**Comment by ianhinder** [comment]
Strictly speaking, the config was only added in the docker branch, which isn't merged.  Shall I create a PR for just the config file, so we can close this issue?

**Comment by aharwood2** [comment]
If you want but is this not the only open issue holding up the docker branch? We could just link this issue to the docker one and use one PR to close them both?

**Comment by ianhinder** [comment]
The docker branch is only a branch at the moment, not a PR, as it's not quite finished.  There is the question of persistence of the database, and ease of updating the code etc that I want to think about a bit more before I create the PR.

**Comment by aharwood2** [comment]
Yes, of course, my question really is are we ready to raise a PR against it which you have answered in the second sentence :) Ok, in this case, I'll just cherry pick the nuget config commit and merge it into my v1.8 development branch.

**Comment by aharwood2** [comment]
This is cherry picked so will move this on as it will be in the next release.
