### ISSUE TITLE
No such table: 'Roles' when running CapX for the first time

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#152]
When running CapX for the first time, I get the following error:

```
ppmtool-ppmtool-1  | info: PPMTool.Program[0]
ppmtool-ppmtool-1  |       Host Created
ppmtool-ppmtool-1  | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
ppmtool-ppmtool-1  |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
ppmtool-ppmtool-1  | info: PPMTool.Startup[0]
ppmtool-ppmtool-1  |       DEVELOPMENT ENVIRONMENT
ppmtool-ppmtool-1  | crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
ppmtool-ppmtool-1  |       Application startup exception
ppmtool-ppmtool-1  |       Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Roles'.
```

My guess is that the migrations code is not currently able to create an empty database from scratch, but needs a "seed" database file to start from.

Is it possible to get such a file, for development purposes?

**Comment by aharwood2** [comment]
When you develop a code-first .NET application, the usual approach is to execute the migrations on the database before you run the app which sets up all the tables. This is easy to accomplish using the EF Core CLI which you should have installed when setting up your .NET dev env? In terms of "seeding" the DB, this is already done in code.

**Comment by aharwood2** [comment]
I should say that I don't want to run migrations at runtime because I quite often want to have the DB at the particular state for testing so that isn't an option. Will mark this as wont fix if that is OK as I don't think there is anything to actually do here, it is a development workflow thing I think.

**Comment by ianhinder** [comment]
Agree with not running migrations at runtime.  Thanks for the pointer to the EF Core CLI. The command I needed was
```
dotnet ef database update -- --environment Development
```
This allows me to initialise the database and launch CapX without any errors!

Is there a way to bypass CAS for local development?

**Comment by aharwood2** [comment]
> Is there a way to bypass CAS for local development?

Yes! There is a build configuration called "Local" which bypasses CAS authentication and signs you in as me with super-user privileges :) When you run, you can pass an argument to dotnet to run this particular build config. If you are using VS, then just choose it from the drop down at the top before pressing play.

**Comment by aharwood2** [comment]
Can this be closed now?
