### ISSUE TITLE
Explain burn-up chart on projects page

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#156]
It would be good to add more explanation about the burn-up chart on the project page.  While writing this issue, I think I have figured out what it is showing, but it took me a while to infer everything!

![image](https://github.com/UoMResearchIT/CapX/assets/213274/8219bdae-8e55-4b7d-8e37-95ec2597218b)

- The blue value line seems to be the amount of effort planned to be expended on the project, calculated from the task data. A label could be "Planned", or equivalent if there is more precise CapX terminology for this.  Is there a difference in what is plotted before and after "Now"? i.e. is the region before "Now" based on "actual hours" numbers, or is the blue line entirely derived from the planned task info?  I think the latter.
- The vertical axis should have a label; it looks like it is "Effort (hrs)" or similar.
- The red vertical line is presumably "Now", and it would be good to label that.
- The horizontal axis doesn't really need a label, though it is good form to have one.
- Is the red horizontal line the total number of hours of effort the project has taken, derived from the "actual hours" recorded in the tasks? A label could then be "Actual".

This is not documented in the [wiki](https://github.com/UoMResearchIT/CapX/wiki/Projects), but with enough annotations, I don't think it would need to be.

I want to answer the question: "Is the project burning up hours at the expected rate?".  Should I look at the intersection of the two red dashed lines, and if this is above the blue line, we are working too hard, and if it is below the blue line, we are not working hard enough?

**Comment by aharwood2** [comment]
Interpretation correct. Will document in the Wiki and see what I can do about the labels.

**Comment by aharwood2** [comment]
Updated the wiki with more information: https://github.com/UoMResearchIT/CapX/wiki/Projects#understanding-the-burn-up-chart
Added chart axis labels in commit [722449c](https://github.com/UoMResearchIT/CapX/commit/772449cdd0410159643291e2ae19d6ddccfce3b7)
