### ISSUE TITLE
Consider not allowing a task to use the "default day rate"

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#157]
Tasks have the option (on by default) of using the "default day rate".  For a task where this is enabled, any change to the default day rate will change the day rate of the task. However, our policy is to fix the day rate for the project, so it should not change in a task when the default day rate changes.  Instead, it might be useful to record the "agreed day rate" at the project level, which gets populated with the default day rate when the project is created, but is not automatically updated.  The PM would set it to whatever was in the request doc.

If we think it is important to have per-task control of the day rate (maybe it could happen that we change the day-rate of a project part-way through for a very long-running project?), then there could be an option in the task to set a custom day rate, rather than using the project day rate.

**Comment by aharwood2** [comment]
Seems sensible yes. Will add it to the queue. After this week I should be able to get back on maintaining CapX again!

**Comment by aharwood2** [comment]
Another good thing about this is that a global day rate would be useful to estimate the planned cost of a task which has no resources assigned to it. At the moment it just shows as zero as it doesn't have a day rate to use which is not that helpful.

**Comment by ianhinder** [comment]
If we had a project-wide day rate, it would be populated from the default one when the project was created. So any created project would have a day rate assigned.

**Comment by aharwood2** [comment]
I think the things that need to be done are:
- [x] add day rate field to project and make required
- [x] remove day rate field from person and people page
- [x] change resource from default rate to project rate and put in brackets so we know what it is
- [x] calculate planned cost of tasks with day rate for resources or day rate from project if resources are set to use default rate
- [x] migration to populate custom project day rates if any currently in use for resources on tasks on the project
