### ISSUE TITLE
Restrict write access to projects

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#159]
It would be useful to prevent edits to projects by users who do not own the project, so that the project owner maintains full visibility of all changes.

A potential problem is that when a project owner is away, another user wouldn't be able to make changes in their absence.  Options include:
1. Have a small number of super-users who can edit all projects;
2. Have the concept of "additional owners", who are not the primary owner, but still have write access to a project.  This means the super-users don't have to make changes themselves (which may be time consuming, e.g. adjusting tasks and making sure everything is correct), but can assign another person write access when needed.

> I see, yes. Somewhere in between your suggestions could be that we allow a small number of superusers access to everything and then the managers are just restricted to editing their own stuff based on ownership? Would you mind @ianhinder creating a new issue for edit restrictions on projects to extend to managers too based on ownership?

_Originally posted by @aharwood2 in https://github.com/UoMResearchIT/CapX/issues/20#issuecomment-1940767038_

**Comment by aharwood2** [comment]
Pages I think need this granular control are:
- [x] AddProject (disable buttons: delete, save)
- [x] AddTask (disable buttons: delete, update and save, add)

**Comment by aharwood2** [comment]
Done, will be in next release.
