### ISSUE TITLE
RTP number and CapX link

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#161]
This may not be an issue in CapX but I'd just like to record this:

When I try to add a new project in RTP board I have to enter a CapX link, but when I add a new project in CapX I need to enter an RTP number. These requests are conflict to each other. 

What I did was to use 0 as RTP number when creating a new project in CapX, used that link to create a new project in RTP board to get an RTP number, and went back to CapX to change the number. It would be good to offer a route for creating new project in both systems.

**Comment by aharwood2** [comment]
I agree that some clarification is needed around the new CapX link field in Jira as it has only recently been added. However, following the process as [documented in the flow chart](https://livemanchesterac.sharepoint.com/:w:/r/sites/UOM-ITS-Research-IT-RSELeadership/Shared%20Documents/RSE%20Leadership/Policies%20and%20Processes/Management%20Policies/[RSE_Project_Demand_And_Monitoring_Process.docx](https://livemanchesterac.sharepoint.com/:w:/r/sites/UOM-ITS-Research-IT-RSELeadership/Shared%20Documents/RSE%20Leadership/Policies%20and%20Processes/Management%20Policies/RSE_Project_Demand_And_Monitoring_Process.docx?d=w69172a2526f9451294818b01765f6669&csf=1&web=1&e=lZTxtU)?d=w69172a2526f9451294818b01765f6669&csf=1&web=1&e=lZTxtU) the CapX entry is not created until the request document is finalised so the RTP card in Jira should already exist before the CapX entry is created. On Jira, the CapX entry field is actually automatically generated -- I couldn't create a read-only field! Apologies, will update the guide to reflect this.

**Comment by aharwood2** [comment]
I also note that CapX Link was required. Have removed this now.
