### ISSUE TITLE
Assignment set in a project disappeared the capacity page

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#169]
I've just found out that for project RTP 167, also I've assigned Hugo to it from 18/03/24 at 50% sometime ago, and it's still there in the project details page, it's not showing if I check Hugo's availability in the capacity page. Not sure if it's a bug or not.

**Comment by aharwood2** [comment]
So it is and it isn't. A side-effect of the "save state" feature seems to be that the default value of "Include Unfunded" gets "corrected" when the page loads for the first time. I suspect that RTP-167 is unfunded and it is just being excluded. I will fix this in the next version, possibly even as a hotfix.
