### ISSUE TITLE
Add Webhook for auto-deployment

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#170]
I have a bash scrip already that can pull the code from Git, sync the DB from production with SSH keys, apply migrations, compile and publish. Might as well use a webhook to have this run the script on the servers automatically. Will need to write the webhook handler on the server in something suitable and have it listen then set up the event on GitHub to send a POST to the endpoint.

**Comment by aharwood2** [comment]
Would make sense for it to integrate with the docker stuff eventually but the environments on the servers are fine as they are for now with SDK installed so will leave this to a future enhancement.

**Comment by aharwood2** [comment]
I can just dump an API controller in to the app itself to handle this maybe? https://stackoverflow.com/questions/70583469/host-web-api-in-blazor-server-application then setup the webhook post in the usual way https://docs.github.com/en/webhooks/using-webhooks/creating-webhooks

**Comment by ianhinder** [comment]
You could use [this](https://github.com/adnanh/webhook) as a webhook listener which can trigger shell commands.  Static binaries provided for different platforms.

**Comment by ianhinder** [comment]
Probably more clean than having the app listen for a webhook which triggers a script which will update the running app!

**Comment by aharwood2** [comment]
> Probably more clean than having the app listen for a webhook which triggers a script which will update the running app!

Oh I don't know, seems clean to me -- good async self-updater use case I'd say.

**Comment by aharwood2** [comment]
> You could use [this](https://github.com/adnanh/webhook) as a webhook listener which can trigger shell commands. Static binaries provided for different platforms.

I was partly curious to see whether I could mix and match patterns effectively in a Blazor server app. Feels iffy to have elements of MVC mixed in with what is essentially MVVM but it is possible and will work. Still, I guess I'll do it the sensible way and run a separate webhook listener... :)

**Comment by aharwood2** [comment]
Had a quick look at this and got the webhook package installed, running as a systemd service and listening on localhost:9000. I've got nginx to listen on 8888 and proxy pass http requests through and this all seems to work when I curl both on 8888 and 9000 but webhooks is complaining in reply to curl that there is "no hook found" even though it looks to be set up correctly and I've not made any typos that I can see. The logs also clear state "1 hook found" and "serving on localhost:9000".

Trying to do a get from a web browser is strange and returns a 307 redirect to https which should complain about being insecure but doesn't so something is not right here. Will need to look at it again when I have a bit more time.

**Comment by aharwood2** [comment]
Released that the CapX servers are behind the VPN so GitHub can't see them anyway. Shelving for now.

Sending a curl POST to both the internal webhook endpoint and via the nginx proxy works as expected. I have to run the service using my user with the `User=` parameter in the service file as it needs to call scripts that sit in my home directory at the moment but this is fine. Webhook is current unsecured though so will need to sort that out once it is internet visible if we proxy CapX to the outside world one day.

**Comment by ianhinder** [comment]
I have used https://smee.io in the past, though there is a heavy warning only to use it in development and not production.  They run a service which provides a public webhook endpoint which you can give to Github, and your client (inside your firewall) then does a long-poll of the smee server and is updated when there is a hook request for your "channel".  Has worked for me.  There are open source variants of it (might even be the same code) which you can self-host.  Starts to be a lot of moving parts, though, with logs to monitor in a lot of different places.  I agree to shelve it for now, as I'm sure you have lots more important things to do!

**Comment by aharwood2** [comment]
I have used Hookdeck before as an intermediary, looks like something similar to Smee? Usually just so I can see what is happening though. I wonder if I can long poll that platform? Never considered a long polling solution but makes total sense! My "tech time" these days is essentially my "outside work time" so yes, don't want to end up down a rabbit hole too often or the family will complain I'm always in the office!

**Comment by aharwood2** [comment]
OK -- I had a brainwave from your suggestion of polling Ian and just binned off the webhook altogether. Instead I've just set up a simple cronjob to every 5 minutes git fetch and determine whether the local branch is behind the remote. If so it build and deploys, if not it does nothing. Problem solved.

**Comment by ianhinder** [comment]
Ah yes, polling, the scourge of the internet :)

Hopefully github doesn't mind, and waiting 5 min isn't too bad considering the frequency of updates.  Nice to have it automated!

[This](https://github.com/orgs/community/discussions/44515) post suggests that git operations (as opposed to github api operations) are not subject to any rate limits, so we're probably OK.
