### ISSUE TITLE
Add more detail to project tooltip in capacity view

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#173]
When trying to find out whether an RSE is available for a project, it is useful to look at their capacity on the capacity view.  This allows me to see when the RSE has capacity.  It would be useful to get a quick glance of information about the project either in the tooltip or the left axis.  In particular, the project manager would be useful, as they should be the first port of call when trying to negotiate for the RSE.  Whether the project is funded or not would also be useful to have there.  (Though maybe that should be shown by a different style of bar for unfunded projects, e.g. with a dashed line around or something).

![image](https://github.com/UoMResearchIT/CapX/assets/213274/267f0289-27c6-47b3-b47c-340b714fa2c6)

**Comment by aharwood2** [comment]
Sure -- we can add some more data to the tooltip. With regards to changing the style of the bar, I wanted to do this as part of #50 but the charting library is very limited so I resorted to showing the information by shading the background of the tooltip instead. I'm considering changing the concept of "provisional" so it isn't just suggested assignments but also covers cases where the project simply isn't funded as I think that would be useful. It is somewhat covered by being able to toggle the switch to remove the unfunded ones from the view but it could be clearer.

**Comment by aharwood2** [comment]
Styling of bars is now done via #182. I will add the name of the PM on the tool tip then as part of this issue to resolve it.

**Comment by aharwood2** [comment]
Straightforward fix for this with tooltips now provide PM information:


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/afbeae8a-56ad-4a45-a71f-3797d21372f3)
