### ISSUE TITLE
Improve UX for fixed start and end tasks

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#177]
The phrases "End date driven" and "Work driven" in the task edit page confuses me.  Do they mean that the task is driven by the specified end date, or that the end date is driven by something else?  I think it is the latter, because when I deselect "End date driven", i am able to change the end date.  But it reads very strongly as the former to me in the page.  "This thing is end-date driven".  The UX here is a bit inconsistent between the start and end date.  For the start date, if the corresponding toggle is selected, I am able to choose the start date, whereas for the end date, if the toggle is selected, I cannot choose it.  This is also made hard to understand by the fact that the end date only ever seems to be editable when the task is "fixed duration".  I don't think anything is buggy here, but it is hard to understand.

Maybe instead we could have "Fixed start" and "Fixed end", and the corresponding reversal of semantics for the toggle?  Maybe even "Fixed end (only for fixed duration tasks)", to make it clear how to fix the end date.

The UI is also confusing, because when one of these toggles is "off", it really looks like it's greyed out and uneditable, even though you can click on it. Whereas a truly greyed out toggle is actually just a lighter shade of blue than an "on" toggle.  

This whole thing has mystified me since I started used CapX!

**Comment by aharwood2** [comment]
The current styling is the [Radzen Standard theme](https://blazor.radzen.com/switch?theme=standard&wcag=true) which produces (admittedly) confusing results for switches:

<img width="229" alt="Screenshot 2024-03-28 144355" src="https://github.com/UoMResearchIT/CapX/assets/8614261/9a38eacf-69cd-4c5a-8b6d-ce11bad8bd61">

Overriding bits of this might be possible but I'm wondering whether it might be easier to just maybe style the text above the switch instead. I'll do a partial PR for the first issue though as that is easier to fix.

**Comment by aharwood2** [comment]
I've added some icons with tooltips when something is disabled which I think is probably sufficient?

**Comment by ianhinder** [comment]
❤️
