### ISSUE TITLE
Monitor uptake of CapX among userbase

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#178]
It would be interesting to see how many people in the department are making use of CapX, now that it has been rolled out generally.  For each user account in the system, we could check to see who has ever successfully logged in (probably this can be found from the logs?).  Some people may not be able to log in, and are not reporting it, which reduces the overall value of the tool.

**Comment by aharwood2** [comment]
Interesting -- what prompted you to ask this? Do you get the impression that the "developer" view is not being used? There are some outstanding issues related to login problems but the reporters have not followed up so perhaps that means they just have given up on the system. Should be easy to discover this once #20 is done. Maybe I'll bump it up the priority list.

**Comment by ianhinder** [comment]
James saying that he wasn't able to log in to CapX.  He's now reported it.

**Comment by aharwood2** [comment]
I think there is a feature in here which would be to add thr last logged in date to the access control DB so will do that first then see what data we get.

**Comment by aharwood2** [comment]
OK -- added the migration. Can't actually test this properly until it is deployed so will merge to dev so it deploys to the test system and I can see if it works when integrated with CAS.
