### ISSUE TITLE
Task end date changes every time Update is clicked

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#181]
For a fixed work task, the End Date keeps getting changed each time I click on "Update".  See this video:

https://github.com/UoMResearchIT/CapX/assets/213274/becc7b82-b7ed-4c9e-939d-b6d36afcf552

**Comment by aharwood2** [comment]
Lovely! Will get on this shortly. Might need a hotfix as this is pretty dangerous to get wrong!

**Comment by aharwood2** [comment]
OK, worked out what is happening here. Fix will be available in the next hotfix. Essentially, I'd updated how resources were added some time back but left the old mapping in. The code works fine assuming a user presses update once with a "staged resource" in place (i.e. it hasn't been saved to the DB yet to get a primary key). If you press update again however, it checks the task model and sees only "staged resources" and goes ahead and adds the resource again. So basically, every subsequent time you click update, the scheduler duplicates all staged resources on the task so the duration roughly halves 😄 Didn't need to be that complicated with the in-line approach so just rewrote it.
