### ISSUE TITLE
CSS styling for different project statuses (provisional/unfunded)

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#182]
It would be really helpful to be able to more easily see the status of projects/allocations on the various screens by styling the chart "bars" accordingly. 

* The Black Box of the charting tool being used is, I gather, difficult to manipulate, but perhaps if an attribute/id/class could be added to each data point and then some JQuery could parse the DOM and pick out all such attributes to add a relevant CSS class after the fact?

**Comment by aharwood2** [comment]
I feel like I looked at this in the past and it wasn't straightforward but happy to look at it again and also see if your suggestion could work too.

**Comment by PhilBradbury** [comment]
The more I think about it (which isn't too much, tbh) the more I think it actually won't work. JQuery would need some way of identifying which control(s) to add the css class details to, and if you could provide some way of identifying them (in such a way that the JQuery method would know which class to add to which control) then you'd simply be able to add the class at that point.

Happy to have a play with it at some point when I get chance though; as you've already looked at it; rather than waste your time. :)

**Comment by aharwood2** [comment]
Making some progress on this now. Needed to split out into two separate series, and colour those with a different fill scheme. Should be able to do something similar for the capacity chart too I think:


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/a52f2e26-1e3d-4e13-bcbd-ad12acda854b)

**Comment by aharwood2** [comment]
- [x] Apply same logic as above to capacity graph in both modes

**Bugs**
- [x] Total row needs to always show at the bottom (see AJ's split where it doesn't) - related to [this bug](https://github.com/apexcharts/apexcharts.js/issues/3796) so might not be fixable.
- [x] Update the hatching logic to show as hatched if project is also not funded, active, maintenance as it might not happen

**Comment by PhilBradbury** [comment]
Nice! Yeah, splitting it up into different "types" looks like the way to go, rather than trying to do it after-the-fact with JQuery. :)

**Comment by aharwood2** [comment]
Done now for capacity charts

![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/66fcbc4b-54e6-48df-b8cb-4d65ca55f61f)

**Comment by aharwood2** [comment]
Also added indicator to projects in the list which have only provisional resource assignments:


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/02586939-9b6a-4711-806f-ff4a66d34a38)
