### ISSUE TITLE
Removing Unmet tasks from the burn-up chart

### ISSUE THREAD

**Issue by AnnAnnFryingPan** [UoMResearchIT/CapX#183]
Would it be possible to exclude the unmet demand from the burn-up chart, so that any met tasks don't get buried in the total (met and unmet) amount.
For an example, see RTP-37

**Comment by aharwood2** [comment]
I think the easiest way to do this would be to add a second line to the graph which computes the burn-up based on the actual allocated amount. That way we can keep the idealised curve as well. Probably needs a doc update as well to state that we should be looking to track against this secondary line and invoice against that line too.

**Comment by aharwood2** [comment]
I think this is going to depend heavily on #128 as we essentially will change the way unmet demand is represented which will be needed in this feature. I will do it for v1.9 but it will be behind the linked issue.

**Comment by aharwood2** [comment]
There is now a new series to take this into account:


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/e9ff2a66-3e0b-4c57-a7da-cc2d0b2f3ef7)
