### ISSUE TITLE
Live update of Innate Codes

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#202]
Currently updating the innate codes in the tool is a manual process of me uploading a file to Firebase storage with all the codes and then the app being restarted to refresh its local cache. Ideally this needs to be dynamic. One option would be for the file to be saved to OneDrive / SharePoint and then have the app use an access token to pull the file every time the list needs to be populated. There would be a short delay while this happens but it is probably worth it. Unfortunately, as Innate does not have a public API there is no way to get the codes out automatically so the export process will still have to be manual.

**Comment by ianhinder** [comment]
I have had some success with Selenium scraping data out of Innate, but you would need to have your Innate credentials stored on whatever server was doing this.

**Comment by aharwood2** [comment]
I've opted to simply go with another DB table and a manual CRUD interface to maintain them. It seemed easier than messing about with a web-scraping solution for now. Just another admin step for me but should take seconds so not really a problem.
