### ISSUE TITLE
Add deployment scripts to repo

### ISSUE THREAD

**Issue by AbbyGavin** [UoMResearchIT/CapX#204]
It might be useful to store the deployment scripts in the repo. Anyone wanting to use this repo as an example for their own system would find it useful. This would need keeping up to date if anything changes though, so it's not ideal but better than nothing.

**Comment by aharwood2** [comment]
Just got access back to the VM so working on this now + documentation.

**Comment by aharwood2** [comment]
@AbbyGavin scripts and the kestrel server systemd service example are on the branch now. Haven't got round to detailed docs yet but you essentially just need to configure them to your needs, drop the kestrel service in the /etc/systemd/system directory and setup nginx as a reverse proxy. You then just tell cron to run the checkdeploy-*.sh script every 10 minutes or so.

**Comment by aharwood2** [comment]
Jobs still to do to finish this off:
- [x] Check readme is sufficient to explain how to use the files
- [x] Update the cron job on the prod and dev boxes to use the files in the repo instead of the local home directory and check it works

**Comment by aharwood2** [comment]
Dropping this out of the current release as not super urgent for now since scripts at least are available with instructions in this issue.
