### ISSUE TITLE
Heads Up Section to Projects Page

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#209]
It would be useful for PMs to be able to see their owned projects at a glance. In the first instance it could be useful for them to just see the ones with warnings on them, for example ones which have provisional resources or ones which are under resourced as these are likely the ones requiring more close monitoring. We could also add a status message for projects with tasks starting within a month and within the past week to make sure people have scheduled meetings if necessary #210.

**Comment by aharwood2** [comment]
Have added a summary section at the top of the page for projects people own so they can quickly see if any action is needed, head to details and head to RTP as required.
![image](https://github.com/UoMResearchIT/CapX/assets/8614261/0d164d24-7414-45f5-9d2d-6eb7a7279290)

**Comment by ianhinder** [comment]
I had thought it would be useful to have a button at the top of the projects page to search for "Projects I manage", which would populate the PM filter with my name.  CapX does remember filters, so you can filter by your own projects and have that view always available, but if you then change the filter to look for something else, you would have to put it back.

I'm not sure whether it makes sense from a UI point of view to have two separate views of the list of projects on the same page.  e.g. you have a link to the RTP card in the top view, but not in the bottom.  Would it make more sense to have a single view, but with your own projects with warnings shown first?

**Comment by aharwood2** [comment]
I don't think so -- the bottom part of the view is a data grid and is designed for in-line searching, filtering etc. which is less likely to be used now we have the "heads-up view" which essentially only serves to highlight issues you need to fix as owner, key things you need to be aware of and shortcuts to access stuff quickly. I could have put these on separate pages of course with the data grid on its own projects page and the heads-up display on a homepage called "dashboard". If you really hate it then you can raise another issue to have it altered :)
