### ISSUE TITLE
Fixed width for side bar

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#225]
Width of the nav-bar changes on every page based on the container size and this can be fixed.

**Comment by aharwood2** [comment]
Seems to be largely the projects page that has this issue so something about the content I suspect that means it won't resize properly.

**Comment by aharwood2** [comment]
@PhilBradbury -- if you have an CSS inspiration that would be great 😄

**Comment by PhilBradbury** [comment]
I'll try to find some time to take a look. CSS isn't really one of my good friends though. We're always fighting. It's not pretty.

**Comment by aharwood2** [comment]
Do you hate it yet?


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/f5dd2727-8b4e-44b7-9f46-63f57b6f1298)

**Comment by aharwood2** [comment]
Nah, I'm kidding. Will probably go with this.

![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/d4dddd3d-d824-4af0-822d-1f403da603b2)

**Comment by PhilBradbury** [comment]
We need to play LFD2 again... purely so I can shoot you for this sort of nonsense. #Kidding #OrAmI 🤣

**Comment by aharwood2** [comment]
Not really related but a note to self: get rid of the "legacy" status icons and move the arrow to the right hand end of the projects grid. Probably should do this for the other grids where they have an edit icon somewhere mid table.
