### ISSUE TITLE
Split capacity view (multiple staff) into separate sections

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#230]
A table of capacity info per user being filtered on would make the screen easier to read.

![Image](https://github.com/UoMResearchIT/CapX/assets/10961727/d8ebe4dc-2649-481d-8aba-bd1742d14246)

**Comment by aharwood2** [comment]
How do you want the Total (All) row presented in this view? In its own chart at the end or do you not really care about that?

**Comment by aharwood2** [comment]
@PhilBradbury -- thoughts on the above question?

**Comment by PhilBradbury** [comment]
Apologies. I'm trying to access it now but am getting this before it crashes back to a Shibboleth page which then tells me my username can't be rocognised. :(

![image](https://github.com/UoMResearchIT/CapX/assets/10961727/09444387-6ed8-4249-9f3b-30872396ffe7)

**Comment by PhilBradbury** [comment]
I don't think there's a need for the "total total" bar given that the "team" dynamic has been removed with the introduction of people being able to work on any project (i.e. not just ones "with their team"). 

Each section would need to keep a shared timeline scale though, as per our conversation on 21/05/24. Having one showing 2 years with the other showing 6 months could be very confusing!

**Comment by aharwood2** [comment]
Needed more JS than I'd have liked and they cannot all share the same chart options object otherwise they don't draw (as I found out reading a GitHub issue for something different)....but, I think I have something that you are after?


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/419f3aed-edbb-4f9a-8176-61b87e5810cf)

**Comment by aharwood2** [comment]
Will merge it over to dev so it deploys to the test system and you can play with it. Have you got your PPAD account fixed yet?

**Comment by PhilBradbury** [comment]
Very nice! Is yours all in red due to your infamy level and the amount of blood you spill each evening? ;)

**Comment by PhilBradbury** [comment]
Have put in a ticket about my PPAD account. Nothing as yet though.
