### ISSUE TITLE
Project page opens on a popup window

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#231]
This is probably just a personal preference, but at present when you click on a project from the main projects list CapX displays the details of the project in a new tab/window. If you are looking at multiple projects you end up with loads of tabs very quickly, and if your browser blocks popups the button doesn't work at all until you specifically enable popups for the session.

I'd like it to display in the same window and instead of a button have a link. That would mean I can right-click if I want to display it in a new window, and the browser won't complain about popups!

**Comment by aharwood2** [comment]
I can hyperlink the title so you can still click the button to open in a new tab? Maybe we need two buttons?

**Comment by ianhinder** [comment]
I had the same problem - clicking on "Details" doesn't work (unless you allow popups).  What is the reason to have a popup rather than a link?  I think people are pretty adept at opening either in the same tab or a different tab depending on what they want to do.

**Comment by aharwood2** [comment]
I found it more convenient when I was testing it out but can either change it back, have a second button or hyperlink the title -- preference?

**Comment by ajerrison-manchester** [comment]
For me a hyperlink would probably be a preference.

**Comment by aharwood2** [comment]
OK -- thanks:


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/504cbd03-2e5a-43ed-bd23-0e599f32a2f9)
