### ISSUE TITLE
Show RSE availability on tooltip in capacity page

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#243]
It would be good to see what an RSE's total availability is for project work when scanning down the capacity view.
<img width="362" alt="image" src="https://github.com/UoMResearchIT/CapX/assets/213274/9f7589a3-e34a-4603-b11c-0adf75c57a90">

In the above, I can see that the RSE is allocated at 0.4, and from the colour I can take a guess at what their availability is, but it would be good to have it explicitly shown in the tooltip.

**Comment by ianhinder** [comment]
2:29 pm to 3:39 pm; 70 minutes.  Is that a record?

**Comment by aharwood2** [comment]
Maybe -- I had it in front of me and it was a one line change so I thought why not!
