### ISSUE TITLE
Add Project: More people fields

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#25]
When adding a project it would be useful to be able to add contact details and role for more than 1 person. Although all projects have a PI, the main contact might well be a postdoc or PM. If they are not based at Manchester then an email address would be useful too.

**Comment by aharwood2** [comment]
OK, that's fair enough. Probably simpler to add a "secondary contact" field rather than messing around with the ability to add "n" contacts unless we really need it. Will add it to the milestone.

**Comment by aharwood2** [comment]
This is sort of covered by linking the CapX entry to the RTP card which in turn links to the Request Doc that contains all the extra detail. Still relevant issue but degrading its priority.

**Comment by aharwood2** [comment]
I wonder now after v1.10 that this is covered by the description and the link to the request doc? Can I close this?

**Comment by rowleya** [comment]
I would suggest this is covered by that, and also by the comments boxes where this could also be added if desired.

**Comment by ajerrison-manchester** [comment]
Yes I think so.
