### ISSUE TITLE
Enable narrowing of RSE and Projects in filter boxes by typing

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#254]
It would be good to be able to type to select the RSE or project in the relevant filter boxes throughout the app.  This is faster than scrolling down, and is fairly standard in dropdowns. It seems to jump to the entry which starts with the letter typed, but it would be nice to do a substring search instead.

**Comment by aharwood2** [comment]
Could you let me know exactly which instances? It will be quicker for me to fix them then! I did this for the Timesheet activity code as the list was long so should be straightforward to do it for the rest I imagine.

**Comment by aharwood2** [comment]
For filter boxes in the data grids these are an easy change to switch all of them to substring searches but do you also want this adding to the dropdowns?

**Comment by ianhinder** [comment]
The main one I miss this for is when filtering the capacity page by RSE.

<img width="736" alt="image" src="https://github.com/UoMResearchIT/CapX/assets/213274/dd2019fb-fd0d-4b7e-8e69-27c3ab286a51">

So I guess yes, for the dropdowns :)  Maybe they could be text fields with autocomplete, rather than dropdowns?
