### ISSUE TITLE
Determine Innate activity automatically

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#264]
New projects have Innate activities with a specific format: S-RES-RTP-${rtpnumber} - {project}.  If there is an Innate code matching this for a given project, CapX could select it automatically.

**Comment by aharwood2** [comment]
I guess this depends on the Innate code already existing in CapX at the time the project is created. This is unlikely to happen in this order I think as we usually only create an Innate Activity when a project is about to start. CapX entries are created much further upstream in the demand pipeline. We could auto-complete when the code is added for any matching projects but I wouldn't want to do this with confirmation from the PM really. Thoughts?

**Comment by ianhinder** [comment]
Ah i see, that explains why it's not done currently. If you think it needs confirmation, then it may as well be done manually, so just leave it as-is.
