### ISSUE TITLE
Add project: multiple payments

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#27]
For most longer term projects payment comes in multiple stages. Might be every financial year, at certain milestones, or just once a certain number of days have been spent. So we'd need a separate screen for 'funds received' I think, to record the funding arriving.

**Comment by ajerrison-manchester** [comment]
Also, we might want to record that the RSE's salary is paid as a PCM instead of journal transfer.

**Comment by aharwood2** [comment]
Hmm, yes, perhaps rather than simply updating the funds received value, we could have that value update from a separate list of transactions. We can then have a page to input a transaction instead so we can see the "payment history". Strikes me that we could delay this until a later milestone?

**Comment by aharwood2** [comment]
I guess this one comes down to whether RTP fulfils this already? I've recently created a new text box on the RTP cards called "Finance Info" so we can keep track of the finance state more clearly there so maybe we can downgrade the priority of this for now?

**Comment by aharwood2** [comment]
Is this covered by #269? Once the finance tracker is there, it will couple invoices to Projects so we can get a finance report out of the system quite easily and see which projects have outstanding invoices? I'd like to close this if it is?

**Comment by ajerrison-manchester** [comment]
Yes (if Konjera is happy to fill it in!)
