### ISSUE TITLE
RTP Feature: Data migration

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#275]
Export of all the Jira data and a standalone migration after all the RPT features are finished to do a one-time migration of data straight into the DB. Considerations:

- Finance Field will not be migrated so this information will simply be added as a note with the finance tag instead.
- Mentions and links will need special handling as they will need resolving and formatting but no email sending to avoid a deluge.
- Images and attachments will be lost so need to flag somewhere to owner to move these to SharePoint manually.

**Comment by aharwood2** [comment]
Currently taking the approach of exporting the XML from Jira, using an online tool to convert it to JSON, using a .NET tool I am writing to:

- [x] Read the JSON from a file
- [x] Deserialise it
- [x] Extract the request doc link and format
- [x] Extract the scrum project link and format
- [x] Extract the description and fomat
- [x] Replace the mentions of people in the comments with badge spans
- [x] Replace the authors with names
- [x] Replace any links to other projects in comments or descriptions with CapX links to project details pages
- [x] Highlight any remaining links to universityofmanchester.atlassian and see if they can be migrated.
- [x] Write new CSV files one with project level information to update the Projects table.
- [x] Write new CSV file to with Finance Info converted to tagged notes to update the Notes table.
- [x] SQL scripts to update the tables in the DB

**Comment by aharwood2** [comment]
Data is ready now. The XML export is first converted to JSON via an online converter (one which preserves the XML attributes as many converters strip them out. I run a console app which then reformats the HTML in the JSON to replicate (as best I can) the data having been input in via CapX. Two pipe separated files are produced with all the necesary information.

Now I just need to write a bash script to install and fire up thr Sqlite command line tool so I can then batch import it all.

When migration time comes, the auto deployment will run as normal but the data will be missing. I'll have to ssh onto the machine to then execute the bash script to import the data. Not worth automating it as this is only time it will need to be run.

**Comment by aharwood2** [comment]
There 3234 notes in Jira that need migrating. Nearly there with it but there are some projects that are not on Capx so cannot be migrated. Will have to create the projects before running the import.

**Comment by aharwood2** [comment]
Process for migration is semi-manual but takes about 10 minutes.
1. Export XML and let it load so it renders
2. View source to remove the HTML rendering
3. Save the XML source
4. Run through JSON converter (https://onlinexmltools.com/convert-xml-to-json) to get JSON with attributes retained
5. Copy to my `JiraXMLConverter` solution directory, update the source code with the filename and run the application
6. Copy two output files to my Ubuntu 22 FS
7. Copy PPMTool DB file from server `.../publish` directory to my Ubuntu 22 FS
8. Create a backup of the PPMTool DB on my Ubuntu 22 FS so it can be backed out if necessary
9. Run `sqlite3` to get a shell
10. Edit filename in `import-data.sql` and use `.read import-data.sql` to run the sql script to do the migration
11. Copy the PPMTool DB file back to `.../publish` directory on the server
12. Run the `publish.sh` script on the server to roll it out

**Comment by PhilBradbury** [comment]
What, no Excel in there?? Very disappointing. 🤣
