### ISSUE TITLE
RTP Feature: Watch project

### ISSUE THREAD

**Issue by rowleya** [UoMResearchIT/CapX#287]
Jira lets people watch a project so they get emailed when things change.  It would be useful to replicate this in the upcoming CapX changes.

**Comment by aharwood2** [comment]
Would you want an email for changes to the notes or an email when any project info changes? The former is pretty straightforward. The latter could be quite involved. What information would be important when watching a project that isn't your own?

**Comment by rowleya** [comment]
Ideally whatever Jira does, but likely comments are enough for most things.  I suppose if you want everyone watching to see something you can always add a comment too...

**Comment by aharwood2** [comment]
Ok, I'll go with the trivial case for now :)

**Comment by aharwood2** [comment]
@PhilBradbury we discussed the failure of EF core to add an appropriate migration earlier with the error "Unable to determine the relationship represented by navigation navigation property...". After various attempts to "trick" the framework with my own manual migrations, I got the database schema correct but then the migration builder refused to generate any further migrations with the above error every time. Finally came across the ["InverseProperty" attribute](https://learn.microsoft.com/en-us/answers/questions/610783/how-to-use-ef-core-when-two-properties-in-the-prin). Apparently, if you have a relationship already between entity A and entity B, even if it is a different type of relationship, EF core can't figure out what to do with the newest one. Solution was to add these attributes on the relevant properties and it gave it enough information to figure out the rest. Annoying, but satisfying, to see the migration builder generate exactly the same migration code as I'd spent 45 minutes writing but at least this is that.

**Comment by rowleya** [comment]
Time spent now is time saved next time ;)

**Comment by PhilBradbury** [comment]
Good to know it's sorted. :)

I was thinking about this last night, and another way (unsure how you'd do it in 'code first' mode though!) would be to have the table linking projects and people to store all such links, but then to have a column which identifies what 'type' of role or releationship it is... i.e. PersonProjectId, PersonId, ProjectId, Role (the latter being "follower" or "owner" for example).
