### ISSUE TITLE
Popup for mentions and tags

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#294]
I should use Radzen Popup for doing the mentions and project tagging and resolve immediately as typing rather than doing it on save. Resolution code can be reused thankfully so not a total waste. This provides a better experience.

**Comment by aharwood2** [comment]
I've had a first go at this but it is unsatisfactory for numerous reasons:
- [x] Popup isn't displayed until focus is lost from the editor so user needs to tab after typing -- JS focus commands don't seem to work so might need to call a JS unfocus command?
- [x] Selecting a person requires a click rather than simply being able to tab it out -- maybe needs a mouse-over / highlight function to maintain a selection and then a listener for a tab to auto-select?
- [x] Manual click required to return to the editor as it does not automatically get focus on close -- can possible use JS to give it focus again?
- [X] When editor regains focus the cursor is inside the badge and cannot be moved outside -- follow the GitHub approach and just add some plain text?
- [x] Subsequent use of the @ character include the whole content thanks to switching back to strings -- the change events don't seem to give me the diff so I can either manual diff or use a hidden character to represent a properly tagged reference or check all @ characters to see if they have a proper short name behind them before showing the popup?
- [x] Need to auto-give focus to the editor when it is made visible.

**Comment by aharwood2** [comment]
I made a start on this @PhilBradbury but got to do some other stuff now. It is pretty miserable for something I'd expect out the box but I take your point about the UX! Trying to get something a bit like GitHub would be good.

**Comment by PhilBradbury** [comment]
Is there a way of having a static list of people by the comment's text entry box that you can click and drag from into the comment, and that's how they are mentioned, perhaps? Just thinking from a UX perspective rather than a coding one, so it may be a complete no-go!

**Comment by aharwood2** [comment]
Sure but I sort of feel that it is not what people expect. The convention is to type the @ character and then use a popup with arrow keys and tabbing I guess (or at least that is how I use it). It needs to be fast to tag someone while typing a message and not interrupt the flow and that needs a bit of faffing to ensure focus is passed around appropriately. More JS I guess...

**Comment by PhilBradbury** [comment]
Agreed. More JS then, as you say. #GoodLuck :)
