### ISSUE TITLE
Cannot add a new task for RTP-228

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#298]
In RTP-228, I've tried to add a new task (Dev 2), starting from 03/09 for 35 hours, and tried to assign to Louise with 30%. But I always got an error "Demand for a task must be greater than zero!". Not sure where I did wrong.

**Comment by aharwood2** [comment]
What did you put in the "Demand" box? Could you add a screen shot to this issue?

**Comment by TheresaTeng** [comment]
Thank you, I misunderstood the "demand", thought it was about the number of working hours a task needs. It's working now.
