### ISSUE TITLE
Tasks: also add 'unallocated'?

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#30]
It probably depends on how we want to display the capacity planner, but it would obviously be useful to look at all unallocated projects too. We could perhaps have a specific flag on the task for this? Might make it easier to report on within the capacity planner.

**Comment by aharwood2** [comment]
How I've implemented the "Capacity" page is probably not ideal and we can re-write if necessary. However, we can easily check to see if a project has unallocated tasks so perhaps we can add a column to the grid on the project page to display that info. We can then easily filter on that page if we wanted to? Needs some planning this one I think.

**Comment by ajerrison-manchester** [comment]
Just adding to this - I think when you add a task it would be helpful to say what %FTE is expected on the task, even if there is no one allocated to it at the moment. For instance I have a project that is awaiting the outcome of a grant application. If successful it would require an RSE for 50% for 2 years, so it would be useful to know how much RSE support is needed. At present all I can show is that it requires an RSE for 2 years, not the percentage. Perhaps it can be solved just by having a RSE called 'Unallocated' and assigning the task to them at whatever percentage?

**Comment by aharwood2** [comment]
Yes that's intesting. A quick and dirty way to do this could be to create a person called "unallocated" and just assign them to it at the required percentage. It would also schedule the tasks out properly to so maybe that should just be the solution?

**Comment by ajerrison-manchester** [comment]
Maybe 'Funded Unallocated' and 'Unfunded Unallocated'?

**Comment by aharwood2** [comment]
> Maybe 'Funded Unallocated' and 'Unfunded Unallocated'?

I guess this level of detail is what the Jira board is for. CapX can probably be simpler?

**Comment by aharwood2** [comment]
Opted to create a person called Unallocated and to use that to schedule out projects that don't have anyone.
