### ISSUE TITLE
Bitwarden browser plugin slows down response of capacity graph

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#302]
I've found that I need to disable the Bitwarden browser plugin before the capacity view responds quickly. 

Replication: 
WIth Bitwarden browser plugin installed (Firefox and Chrome) and active go to the capacity page. The panel with the capacity bar graph will take many tens of seconds to respond, unless you react to the Firefox message complaining that the plugin is slowing the site down. If you 'stop' the plugin the capacity graph responds normally.. Chrome is slightly quicker with the plugin active but doesn't pop-up a warning message - I have to go into the settings to disable it and then it works OK.

I don't know if this is really a problem with CapX but you asked me to log it!

The first place I'd look is to see whether Bitwarden's plugin thinks the view is actaully a new page, so is scanning for new stuff. If it is then it may be possible to modify Capx to avoid the problem. Or I try another password manager - I just don't particularly want to swap to a new one!

**Comment by aharwood2** [comment]
Updated added to the readme.
