### ISSUE TITLE
Add reminder dates to comments

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#309]
With the comment functionality now being transferred from JIRA to CapX I'd like to see reminder dates added:

- There could either be a separate 'todo' list on the project or,
- There could be a date against a comment

The comment or todo view could be ordered to highlight upcoming reminders, or do something like JIRA and email the owner when something is due.

**Comment by aharwood2** [comment]
Jira at the moment only has the one Due Date field -- is this sufficient or would it be better to be able to "flag a comment" and then you end up with multiple due dates?

Also, if I do this as part of v1.10 I can migrate existing due dates but it will delay the release of this version and I wouldn't know which comment to put them on. I can delay it to v1.11 and not worry about migration and then people can reset them manually.

I'm leaning towards the flagging comments approach:
- [x] Add due date and completed dates to notes model
- [x] Re-open task if completed
- [x] UI button to add / remove due date and mark complete (permission restricted to PM)
- [x] Add sort by due date switch
- [x] Add filter by due date switch
- [x] Add due date to project card and click to view the note via query param

**Comment by ajerrison-manchester** [comment]
I found JIRA's method a bit limiting so would prefer the date on the comment approach if feasible.
