### ISSUE TITLE
Improve wording in absence notifications

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#312]
When a colleague comes back from being absent, the email currently says

> Dear Ian Hinder,
>
> The following people have had changes made to absence records which affect one or more of your projects:
>
> XXX
> 
> YY is absent from ZZ to ZZ (Modified).
>
> You may need to take action to replan your project or notify your customer.
> 
>Sent from CapX

It is not clear from this that the colleague is back at work.  Maybe it could be modified to make this clearer that if there is an end date, then the absence is completed.

**Comment by aharwood2** [comment]
Differentiates now between general modified and specifically a change in the end date:

![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/485b1966-7ba2-4644-8bc3-938e50dda186)

Does not explicitly say "Returned to Work" as this could be a addition of an end date on someone's holiday so didn't seem appropriate. I think this is OK for now.
