### ISSUE TITLE
Duplicated results in Availability Query

### ISSUE THREAD

**Issue by SJaffa** [UoMResearchIT/CapX#322]
When running an availability query the people in the results table all seem to show two rows for the same person/dates/FTE.

<img width="1199" alt="Screenshot 2024-06-24 at 14 21 35" src="https://github.com/UoMResearchIT/CapX/assets/13678317/848306cd-ac5d-4cf8-b0c5-fcee95c9f04d">

System details:
- macOS v14.5
- Firefox v127.0.1

**Comment by aharwood2** [comment]
OK thanks. Bumping to v11 as I think I'll get the critical bug fixes out first this week.

**Comment by SJaffa** [comment]
This seems to have stopped happening, did you fix any possibly realted bugs?

**Comment by aharwood2** [comment]
No but that just makes it more annoying! :)

**Comment by aharwood2** [comment]
I'll bump this to the next version for now as I want to get the hotfix out before I go on leave.

**Comment by aharwood2** [comment]
I had some weird behaviour with this feature too where it didn't show me any results but it should have done according to the graph. It may be that the feature itself is superseded by #94 and related issues so might not be worth trying too hard to fix if I work on those next. In all honesty it is an old feature now and doesn't seem to be widely used. Most people seem to just use the graphical representation. Will still take a look and decide either way on what to do with it.

**Comment by aharwood2** [comment]
I may have found the issue here. There is a definite race condition. I've fixed this but the Unfunded switch does appear to toggle now so need to investigate further.
