### ISSUE TITLE
Individual RSE capacity view load representation

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#328]
The capacity view page for a single RSE shows a bar for each project, and colour codes the individual bars in the same colour scheme as is used for the whole team capacity view.  This has green for <50%, indicating that the person has a lot of availability.  Grey is 100% capacity, indicating that everything is OK and no action needs to be taken.  And red for overloaded RSEs.  This colour scheme is useful for the whole-team capacity view, where a single bar represents a person, whose load is represented by the colour of the bar.

However, when you drill down to an individual RSE, I think the colour scheme is not so useful.  You then get a bar for each project, and what you really want is a colour scheme that shows the load contributed by that project.  It's not "wrong" as it is, but the colours don't help you understand the relative contribution of each project.

For example, for this RSE,

<img width="937" alt="image" src="https://github.com/UoMResearchIT/CapX/assets/213274/9c077881-83ba-441c-af09-2296968db562">

there are a lot of heavy green bars, which are mostly projects in maintenance with something like 0.01 FTE, but visually they dominate the chart.

It would be helpful if projects with only 0.01 FTE could be in a pale grey, and projects with 0.4 FTE could be in green, indicating that they are at the "ideal" level of load that we aim for.  We could then interpolate between pale grey and green for things in between. Projects higher than 0.4 maybe could start to be pink or red.  The "total" bar at the bottom would remain unchanged.

I appreciate that this would then mean we have two colour schemes on the same chart, and I'm not sure how to solve that. Maybe the "total" bar should be a different chart, with its own colour scheme.

Maybe the individual projects should have a different way than colour to represent their load contribution, e.g. the height of the bar could represent that (though I'm guessing the plotting library might not be able to do that).

Now that I've written this, I'm wondering whether the whole-team capacity view colours should be rethought. Would it make sense to have grey there also for a low loading?  Green for ideal load (i.e. their availability), and pink and red for overload?  Essentially I'm proposing that visually it might be more intuitive to swap the green and grey.

Thoughts?

**Comment by aharwood2** [comment]
I love your issue descriptions Ian, you always manage to talk yourself into a different proposal by the time you get to the end 😁 

Could do with some discussion among the user base perhaps. The colour scheme we have came about from #59. Prior to this we used to just have a simple "under", "ideal", "over" scheme which was of limited use for different reasons.

We could always support multiple colour schemes and allow people to choose which one they want to use too. Maybe worth capturing this in the PSM meeting?

**Comment by aharwood2** [comment]
I'm leaning here towards: when in project mode, the shading is used to indicate the relative load of each project with respect to the total. The total bar will use shading that indicates whether a person is properly allocated as usual (and as per "people mode"). I think that gets across what is required?

The question remains as to what colour scheme to use -- perhaps a cool-hot type scheme?

**Comment by aharwood2** [comment]
Started with this but it is getting complicated. Things to fix:
- [x] Tooltip must be varied between total row and project rows in the same way colour maps are
- [x] Not convinced the sum of assignments is correct so project row colour grading is wrong -- check percentages.

**Comment by aharwood2** [comment]
How about this? 

![Image](https://github.com/user-attachments/assets/ab778510-6719-4be7-93f6-fccdba401ac0)

**Comment by aharwood2** [comment]
Or maybe this:

![Image](https://github.com/user-attachments/assets/3e3beb32-1e9b-4074-98c6-ab20e0000b83)
