### ISSUE TITLE
Add project: also have management assignments?

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#33]
We could either just opt to add RSE leads as 50% capacity, or to see a truer picture of team capacity we could add them as 100% but also record management assignments as projects within the capacity planner. This would require a new kind of 'project' which has no end date and is fully funded.

**Comment by aharwood2** [comment]
I think when I first did this I assumed the former which is probably fine but if we build a management fee etc. into the day rate then it may be that the numbers don't add up. Will have to think about this going forward but probably one that should be documented for now saying RSE leads are only to be set to 0.5 FTE availability (or I guess that should be 0.42 FTE if you deduct holidays etc. 😬

**Comment by aharwood2** [comment]
I think, although we have a task setup for management, I actually prefer the alternative approach by just making leads available for 0.42FTE of technical allocation vs a standard RSE who is available 0.84FTE so I won't take any action on this one.
