### ISSUE TITLE
Better docs for quick access to project page from capacity view

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#331]
When looking at the capacity view for an individual RSE, it would be convenient to have quick access to the individual project pages, e.g. by clicking on the project names.

**Comment by aharwood2** [comment]
If you click the bar on the chart it should take you to the project details page. Is that what you mean? If so then I need to improve the documentation.

**Comment by ianhinder** [comment]
Ah yes, that works.  Thanks! I guess I didn't go looking into the documentation - I don't know if it's easy to make this more discoverable.  The fact that the bar highlights when you hover indicates to me that it is going to go somewhere when you click it.

**Comment by aharwood2** [comment]
Great! Will check the documentation for this in any case.

**Comment by aharwood2** [comment]
Have updated the wiki to make this clearer.
