### ISSUE TITLE
Inconsistent terminology between warning message and UI

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#333]
The project edit page refers to a "Scrum project", but the warning about a missing link refers to a "project board".  Jia didn't know what this was referring to, and when she asked, I initially thought it might have been talking about the JIRA RTP card link. We should use consistent terminology throughout. I would stick to "Project board", since it's possible we would track projects which don't use scrum, for whatever reason.

```
This project has started but has no link to its project board!
```
![image](https://github.com/UoMResearchIT/CapX/assets/213274/ca15c9f3-53f5-40f6-ad2f-ff374ab824b9)

**Comment by aharwood2** [comment]
I think I'll stick with "scrum project" although I accept there may be some projects that might end up being just Kanban or might connect to  other project planners that are using something other than scrum but these should be minority cases. It is important at least for now to get people thinking in terms of scrum projects.
