### ISSUE TITLE
Note notifications should show changes

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#335]
I just received an email notification from CapX telling me that Adrian had modified a note I had made on one of my projects. I think the change was to add the Finance Info tag, but I'm not sure, because the email doesn't say what the change was. It would probably be sufficient to include a copy of the old note below the new one, if a diff is not worth implementing.

**Comment by aharwood2** [comment]
More faffy than it seems to do this which is why it wasn't in v10 but happy to plan it in for later on.

**Comment by ianhinder** [comment]
I guessed that you probably only get to the notification code after the change has happened, so you won't be able to easily get the previous version?
