### ISSUE TITLE
Incorrect comment attribution

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#336]
For https://balex.itservices.manchester.ac.uk/projectdetails/26, the first comment in the log has been attributed to me, back in 2022, when it definitely was not written by me.  Maybe something has defaulted to the current project manager?

**Comment by aharwood2** [comment]
As part of the migration, the first comment in every log is a migration of the "Finance Info" box on Jira with the date set to the project start date. This seemed the most sensible thing to do. It probably just used the current PM as author or if there wasn't one set, me probably. Is it an issue?

**Comment by ianhinder** [comment]
No - I only reported it in case it was a symptom of something going wrong in the conversion.  If it's understood, then it's fine.

**Comment by aharwood2** [comment]
Ok great, thanks Ian. Will close.
