### ISSUE TITLE
Cannot insert a link in a note

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#338]
I just tried to insert a hyperlink into a note (for a link to an invoice), but when clicking on the Insert Link button with some text highlighted, nothing happened. It also didn't do anything when nothing was highlighted. Bold worked, so it seems that formatting is supported here.
<img width="323" alt="image" src="https://github.com/UoMResearchIT/CapX/assets/213274/b0ca7218-0453-4fb8-aff4-d52cb40ba2fc">

**Comment by aharwood2** [comment]
So I just had a fiddle on a note you recently posted and I can edit the source OK. Possibly something to do with the component setup. Will look into it.
