### ISSUE TITLE
View Improvements to Capacity Planner

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#34]
At the moment the capacity planner lists capacity of RSEs, which is useful. I'd also like one that lists the capacity of projects at a glance, including those projects that don't currently have enough allocation and some indicator of the grant status of that project (e.g. submitted, waiting outcome etc).

- [x] RSE view -- what we currently have where we can see people's allocations vs time with the colouring indicating how allocated they are. Including #50, we would also be able to see when that allocation is provisional / unconfirmed.
- [x] Portfolio view -- all the projects for a particular portfolio vs time with the colouring indicating how much FTE is currently unassigned. We can also use the output of #50 to indicate if it is provisional or not.
- [x] Bar at the bottom of the graph which represents the summation of all the bars above it e.g. a total row

**Comment by aharwood2** [comment]
Ah OK, so I guess this links in with #32 . Essentialy different types of charts for the same set of data? It also links in with #30.  As mentioned on #30 it might be better to have this available through the projects summary page instead as a filterable column. Or maybe it can be on both. I guess we need a dropdown on the page that allows you to choose different views of the capacity data. Any thoughts on exactly what you would like to see? Project vs time and coloured by planned effort vs budget?

**Comment by ajerrison-manchester** [comment]
Possibly related to this idea - I'd like to be able to click on an RSE on the capacity planner view in order to find out what they are allocated to. It would be especially useful if someone is overallocated. 

With the project view I suppose I'd just like to see at a glance all the FBMH projects with a capacity visualisation. Simply start time and required FTE along with how much FTE has actually been allocated.

**Comment by aharwood2** [comment]
So we really need are the tasks I've now added to the description.

**Comment by aharwood2** [comment]
> Possibly related to this idea - I'd like to be able to click on an RSE on the capacity planner view in order to find out what they are allocated to. It would be especially useful if someone is overallocated.

This might need to be a separate issue as it is basically "can I add a hyperlink to the Y-axis labels on the chart". This is going to be governed by the library / API. If we can't do it directly then it may need some work doing on the library and could get long-winded so best track this on a separate issue I think -- see #79.

**Comment by aharwood2** [comment]
Added the requirement for a total row that has come up in discussions but not made it as an issue in its own right. Modified the title to make more generic.

**Comment by aharwood2** [comment]
I'm wondering whether the "Portfolio View" really ought to just be the PM view now since portfolios and less meaningful now than they use to be? I guess this also ties into #115 so I'll probably do that first then we can make the filter work on that list instead.

**Comment by aharwood2** [comment]
To the final feature of this -- the total row -- I think I'm going to have no choice but to write a brand new processing method that gets invoked after the original chart has been generated that post-processes the chart data to generate the total row. It will have to take in a collection of series data and then either march through day by day to generate new blocks summing the values as it goes I think.

**Comment by aharwood2** [comment]
OK, I've done the last one of these so I'm going to consider this done for now in the next release:
<img width="1093" alt="Screenshot 2023-11-10 at 11 09 40" src="https://github.com/UoMResearchIT/CapX/assets/8614261/d6e5a5e2-7598-48fc-9bec-032d64cf545b">
