### ISSUE TITLE
'Done' button on due note only seems to work when 'Show only note due' filter is on.

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#343]
On the notes on the project detail screen you can add a due date to create a task. When the task is complete you then click the 'Done' button to show it is done.

I've found that if I click the Done button with no filter on the notes then the application reports an error and asks me to reload. However if I filter the notes to show only those that are due, and then press Done, it updates the status correctly.

Confusingly this doesn't always seem to be the case - for instance if I reopen the note after marking it done I can then use the Done button fine, regardless of filtering. 

Perhaps an initialisation thing?

**Comment by aharwood2** [comment]
Perhaps related to #339 ?

**Comment by ajerrison-manchester** [comment]
Yes looks similar. Probably can be merged!
