### ISSUE TITLE
Add 'PreSubmission' option to Project Status

### ISSUE THREAD

**Issue by douglowe** [UoMResearchIT/CapX#352]
Can we have a new status, replicating the behaviour in JIRA, which indicates that projects are in the requirement gathering / pre-submission period?

**Comment by aharwood2** [comment]
The options can be something like the following perhaps?
- New Request
- Awaiting Submission
- Awaiting Outcome

These would replace the current "Funded" option.

Things to consider:
1. All existing records would just be migrated to "Awaiting Outcome" which will probably be wrong for a lot of them but they can be manually corrected by project owner.
2. All enum values will move on by 2. Funded = 1 would correct to 3 etc. We can write a DB migration to do this as part of the feature.
