### ISSUE TITLE
Adjust 'Note Due' display so it shows notes due in the future (7 days time?)

### ISSUE THREAD

**Issue by douglowe** [UoMResearchIT/CapX#353]
Add a 'medium urgency' feature to the 'Note Due' display on the main project page, so that notes which are due within the next 7 days (or other appropriate period) are flagged with an orange colour, in the same location as the current note due indicator.

**Comment by aharwood2** [comment]
Sure sounds reasonable. Can probably have a couple of boxes but need to have a think about the layout.

**Comment by aharwood2** [comment]
I guess we can have an item due (amber) and then an item overdue (red)?
