### ISSUE TITLE
Absence Notification lists no one

### ISSUE THREAD

**Issue by rowleya** [UoMResearchIT/CapX#362]
I received the following email:
```
Dear Andrew Rowley,
The following absence records have changed. Your projects are not affected, but as a manager you are being notified as a courtesy:
Sent from CapX
```

I assume this should have the person in question listed...

**Comment by rowleya** [comment]
This could have been a user error - from Teams, Anja added a record with no-one and no start date by accident.  This might then be the real bug!

**Comment by aharwood2** [comment]
Doesn't look to be that the email sender is not work but actually that it is firing any time anyone presses save even if they didn't add a record.

**Comment by AnjaLeBlanc** [comment]
I edited 
![image](https://github.com/UoMResearchIT/CapX/assets/2316693/33d9625e-d5aa-4f61-b5f1-0ea797c9b2bb)
by just typing the name and selecting the start data and pressed save rather than starting with add.

**Comment by ianhinder** [comment]
Is this a confusion between filters at the top of the table, and having to Add a record?  I have had that problem in the past with other parts of CapX, where there is a table with headings but no records, and I have started typing the details of the record I want to add into the heading filter boxes, rather than clicking Add.

**Comment by AnjaLeBlanc** [comment]
Suggestion: fix by not showing any parts of an empty table.

**Comment by aharwood2** [comment]
Can look into adding this behaviour for all the data grids to avoid the confusion but I also think that there is work to be done on the email service as it should be smarter when determining whether to send an email or not: i.e. if the list of absentees is blank it shouldn't send it.
- [x] Hide table when there are no records, but show again when in "Add Mode" and hide again if "Add Mode" cancelled and table is still empty.
- [x] Have Email Service check that there is content in the email, if not, don't send anything.

**Comment by aharwood2** [comment]
Was easier to just hide the filter row when there is no data. Also added a check for whether there has been any changes or not before deciding to send emails.

**Comment by aharwood2** [comment]
Also made this change to all data grids in CapX.
