### ISSUE TITLE
Review list of email recipients for absence notifications

### ISSUE THREAD

**Issue by AnjaLeBlanc** [UoMResearchIT/CapX#363]
From the list of OoO messages on an absence notifications, people on long term leave (maternity leave/carer break) are receiving the notifications as well.

Should they?

**Comment by aharwood2** [comment]
I guess the question is, at the moment, CapX doesn't know they are on long-term leave. Should it? How would it decide? We could perhaps add a switch on the access page to manually disable notifications for an individual and then we can decide whether we want to turn them off for someone or not?

**Comment by aharwood2** [comment]
I have set a rule on the RSE mailbox to move any auto-reply to CapX messages to my inbox rather than the shared mailbox. It doesn't necessarily address the issue you raise but it buries it at least!

**Comment by SJaffa** [comment]
Related but possibly separate question:

I thought the idea with the absence notifications was that it would email someone's line manager or their project managers when they log an absence, but I am getting emails when anyone in the group logs an absence, which is going to end up with me auto-deleting them and missing the important ones. Is there a plan to change this?

**Comment by aharwood2** [comment]
@SJaffa CapX doesn't know about line manager relationships so that feature was never a thing. Instead, when it was originally launched, it used to just email those PMs whose projects were affected. Then it was decided that all managers should know about all absences in case PMs were off so it ended up being an email sent to all managers but the email was formatted differently -- if you have affected projects then you get a different email than if you are being told as a courtesy. We can debate it at a PSM meeting if you want?

**Comment by SJaffa** [comment]
I think it would be good to check with the group if the usefulness of knowing when your devs are away is, on balance, more or less than the annoyance of pointless emails. I'll make a note in my PSM update and see what people think.

**Comment by ianhinder** [comment]
I find the volume of emails about absences to be fine at the moment, and it is generally useful to know when people are off. So my vote would be to keep the feature as it is. If it turns out that this is what we do, then maybe an email filter rule for the people you are interested in could be the way forward, @SJaffa?

**Comment by AnjaLeBlanc** [comment]
Suggestion: only if a manager is off every other manager is being emailed; otherwise only if people who work for one of your projects will be emailed.

**Comment by TheresaTeng** [comment]
If an RSE has been assigned to a project that hasn't started yet but will do soon (need to define "soon"), it would be useful for the project manager to get a notification, so for example a kick off meeting won't be arranged for the time the RSE will be off. It happened in the past. So it makes sense to not limited the notification to *current* PMs.

If an RSE is working on a project with their RSA time, i.e. they are not assigned to that project, does it mean the relevant PM won't get a notification? 

Sending a notification in time relies on line managers to put the absence info into CapX in time. Line managers may need to get to the habit to do so once they approve a leave booking.

**Comment by aharwood2** [comment]
> If an RSE has been assigned to a project that hasn't started yet but will do soon (need to define "soon"), it would be useful for the project manager to get a notification, so for example a kick off meeting won't be arranged for the time the RSE will be off. It happened in the past. So it makes sense to not limited the notification to _current_ PMs.

The email notification is limited to "affected PMs" defined as PMs who own an "affected project" - see https://github.com/UoMResearchIT/CapX/blob/6dd18a063937139a3fcebdf2c3fecf5cb80384da/PPMTool/Services/EmailService.cs#L80
An affected project is one which has a subtask with a resource assigned to it who is in the absence list and the person is absence within 7 days of the start.
https://github.com/UoMResearchIT/CapX/blob/6dd18a063937139a3fcebdf2c3fecf5cb80384da/PPMTool/Data/Entities/SubTask.cs#L406

The warning that appears on the card when a resource is absent and a task is a week away from starting follows the same logic - see https://github.com/UoMResearchIT/CapX/blob/6dd18a063937139a3fcebdf2c3fecf5cb80384da/PPMTool/Data/Entities/Project.cs#L89

> If an RSE is working on a project with their RSA time, i.e. they are not assigned to that project, does it mean the relevant PM won't get a notification?

Sure, this is a problem but hopefully rare. If an RSA is working on a project, that project has serious problems and is costing us money so we should be shutting it down quickly. I know there are exceptions but CapX isn't really built to track non-billable project work so this falls through the cracks admittedly.
 
> Sending a notification in time relies on line managers to put the absence info into CapX in time. Line managers may need to get to the habit to do so once they approve a leave booking.

Agreed -- this is a process things we all need to get into the habit of doing when people request leave or report in sick.
