### ISSUE TITLE
CapX Burn-Up Chart Displaying Wrong Planned Work?

### ISSUE THREAD

**Issue by douglowe** [UoMResearchIT/CapX#364]
I've entered the planned work for the first part of this project as 35 hours. This is shown correctly in the Tasks, but in the Burn-Up Chart it shows as 28 hours of Planned Work. The Actuals are shown correctly though (at 35.25 hours) - making it look like we have overspent on the project.

Is this a bug, or have I entered some data wrong somewhere?

https://balex.itservices.manchester.ac.uk/projectdetails/212

**Comment by aharwood2** [comment]
I did change the burn-up chart a little while back as part of #200 -- it is possible that there is some mistake there in the code. I'll investigate.

**Comment by aharwood2** [comment]
Had an `if` instead of an `else if`. Fixed in next release.
