### ISSUE TITLE
Make it quicker to switch between projects

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#378]
Currently, as we discussed recently, the display of the main Projects page is slow because it does a lot of (possibly-could-be-optimised) database queries. This means that switching quickly to a given project is not possible. I frequently want to access the project page of any given project. One way to do this could be to have links to the projects I manage listed in the sidebar under the page links.

![image](https://github.com/user-attachments/assets/51ad7b7d-8c72-4891-b2ea-9b3b16e8c9ae)

This would just be a straight list (ie RTP code plus project name, maybe line-wrapped).

EDIT:

Adding task list for this issue
- [x] Create a QuickAccess component (maybe in the header bar rather than the sidebar?) which is auto-complete search box.
- [x] Box auto-complete source can be people or projects and clicking will navigate to appropriate project details or person details page.
- [x] From the person details page, a button (near the top, easy to click) which took you to the capacity page with that person selected.

**Comment by aharwood2** [comment]
OK - I'm open to a quick access menu, sure. Would you just want it to show projects you own? Would you want any status information on it or just a straight link to the details page?

**Comment by ianhinder** [comment]
I think a straight link to the details page would be sufficient. If possible it would be good to get the project title in there as well as the RTP code, as I still don't really think in terms of RTP codes for my projects. Want to avoid database lookups for the sidebar!

**Comment by ianhinder** [comment]
And to answer your other question: the vast majority of the time, I am looking for the projects I manage. For those cases where I want another one, I can go through the main Projects page.

Though a little box in the sidebar with a place to type an RTP code and go there straight wouldn't be bad! maybe a generic search box where you could type someone's initials, or RTP-XYZ, and be taken directly to the thing. I noticed you using query parameters in the URL bar - this could replace that.

**Comment by rowleya** [comment]
Without really knowing much more about Blazor than I saw in the presentation yesterday, but having other things that use databases, would it make sense for there to be a ProjectService.getSummary function which doesn't do as much database querying but gets enough info for the Project list view?  I can see that the getAll function seems to do a lot of "including" things that are probably not relevant to the list: 
https://github.com/UoMResearchIT/CapX/blob/bf5ccc559f646f1c528a9e9ce61aa3424f92d83f/PPMTool/Services/ProjectService.cs#L94-L105

If those are just not "included" does that make the list faster?

**Comment by aharwood2** [comment]
> Without really knowing much more about Blazor than I saw in the presentation yesterday, but having other things that use databases, would it make sense for there to be a ProjectService.getSummary function which doesn't do as much database querying but gets enough info for the Project list view? I can see that the getAll function seems to do a lot of "including" things that are probably not relevant to the list:
> 
> https://github.com/UoMResearchIT/CapX/blob/bf5ccc559f646f1c528a9e9ce61aa3424f92d83f/PPMTool/Services/ProjectService.cs#L94-L105
> 
> If those are just not "included" does that make the list faster?

Absolutely, I say as much on #301 . Every `.Include` and `.ThenInclude` essentially does a SQL `JOIN` which means it has to go look up another table and join the result so after a while it gets super slow. It is just lazy to be honest and it wasn't really an issue until usage patterns means it damages the UX which is happening about now I guess.

**Comment by aharwood2** [comment]
@ianhinder given that the performance of the main projects page is improved, would you still want this feature now?

**Comment by ianhinder** [comment]
I think it would be nice, yes.

**Comment by ianhinder** [comment]
Updating my request, I think the following would be useful in the sidebar:
- A list of projects I manage, with the RTP code and the name, in a compact form, where clicking on one of the projects takes you directly to the project details page for that project
- A text box which accepted various things and took you to them. e.g. an RTP number or the string "RTP-XYZ" would take you to the project details page, someone's initials or part of their name would take you to the person page.

And what I almost always want when referring to a person is their availability, so another feature could be:
- From the person details page, a button (near the top, easy to click) which took you to the capacity page with that person selected.

**Comment by aharwood2** [comment]
I've created the auto-complete search box - the "magic bar". However, these usually work by have a constant source that is then simply filtered. As the magic bar exists in the layout not the page, it will never be refreshed during the lifetime of the session. This means if someone edits a project or person or adds new ones this data will not propagate to the cached source of the magic bar. We have two options, I think, a) wire the magic bar up so that any update or add methods to people or projects calls back to the layout and asks the magic bar to update its source (most efficient but complex implementation); b) load the source dynamically based on what the user types in the box (thrashes the DB with reads but easiest to implement). I'll try b) first and then if it is terrible in performance will switch to a).

**Comment by ianhinder** [comment]
Instead of having it work via autocomplete, can it be a simple text box which, when the user presses Enter, queries the backend with the string, and there is a method in the backend which decides if it's a project or a person etc, and then returns the URL? i.e. just like a form?

**Comment by aharwood2** [comment]
> Instead of having it work via autocomplete, can it be a simple text box which, when the user presses Enter, queries the backend with the string, and there is a method in the backend which decides if it's a project or a person etc, and then returns the URL? i.e. just like a form?

OK -- how would you want it to respond if it can't find a match? What about multiple matches and it can't decide what to do?

**Comment by ianhinder** [comment]
I was thinking of it like a search engine, so it could return a page of possible matches if there wasn't an unambiguous one. But this may be too much to implement now, so maybe return an error message? It would also introduce either an additional click (from the results page), or an uncertainly in the UX between whether you would get a results page or taken to the result immediately.

Now I think it through, maybe having it the way you originally said make the most sense, and is an easier way to deal with the issues of nMatches != 1. 

So I take back the suggestion, and suggest you go with what you originally proposed :)

**Comment by aharwood2** [comment]
I've put together a reasonable stab at this I think. Could be improved but I find myself using it now during testing to quickly move around the pages so it offers some benefit over the menus I think. Will be on the test server shortly.
