### ISSUE TITLE
Not sure if the number of days is quite right

### ISSUE THREAD

**Issue by rowleya** [UoMResearchIT/CapX#380]
There are a number of calculations that use "Round" for number of days, but should probably use "Ceiling", as any fraction of a day should probably be calculated as a day.  Additionally, this should avoid needing to add 1 in some places once done, as the ceil will already account for that.  These are all in this file:
https://github.com/UoMResearchIT/CapX/blob/dev/PPMTool/Data/Entities/SubTask.cs

Lines I have found that could do to be Math.Ceiling and/or remove +1:
https://github.com/UoMResearchIT/CapX/blob/dev/PPMTool/Data/Entities/SubTask.cs#L282
https://github.com/UoMResearchIT/CapX/blob/dev/PPMTool/Data/Entities/SubTask.cs#L296
https://github.com/UoMResearchIT/CapX/blob/dev/PPMTool/Data/Entities/SubTask.cs#L300
https://github.com/UoMResearchIT/CapX/blob/dev/PPMTool/Data/Entities/SubTask.cs#L323
https://github.com/UoMResearchIT/CapX/blob/dev/PPMTool/Data/Entities/SubTask.cs#L333

**Comment by aharwood2** [comment]
What is the issue that you think these lines are causing? At the moment this is a proposed solution to an unknown problem! 😄

**Comment by rowleya** [comment]
Ah sorry, I was looking at how the calculations were done to understand them a bit better, and came across these the issue is that the number of days for a project is often out by one. 

Simple Examples:
 - Fixed work project for 7 hours at 1FTE = 1 billable day (correct) = 3 days duration (wrong - should be Ceiling(1/220 * 365) = 2)
 - Fixed duration project with fixed start and end date one day apart 1FTE = 2 days duration (correct I think) = 1 billable day (wrong - should be Ceiling(2/356 * 220 = 2).
 - Fixed work priject for 3 hours at 1FTE = 0 billable days (I assume incorrect - probably because 3 hours < 0.5 day, but Ceiling would make it 1 day) = 1 day duration (that one looks OK, probably because it added 1, but note that 0.5/220 * 365 also = 1, which I think would be correct).

I would guess that the last example above also depends what you want to do with a project where the start and end day is the same date.  It does have an effect on longer projects of course, but the above are maybe easier to follow.

I would suggest this is not super-critical, but then if you are going to use any of the numbers for financial calculations, this will probably make them more accurate / more likely to match up with external calculations.

**Comment by aharwood2** [comment]
I've had a look at this and there are some instances where you will get fractions of a day that are probably best rounded up so I've adjusted those. However, when comparing two dates, you should only get whole numbers of days -- the round was used to avoid situations where old DB entries might also have time information (I fixed this in later versions) which cause fractional days to appear where they shouldn't. In those cases, I think the round is appropriate as it rounds any fraction of a day downwards to get values that you would get if the time component was midnight (zero). I'm curious to see if the adjustments have fixed the issue so when this rolls out to the dev system, if you could check that would be good.

**Comment by rowleya** [comment]
I think there are still a couple of issues.  For example:

A Fixed Work 7 hour project at 1 FTE is 1 billable day (correct) but 3 days duration (I think it should be 2 as 1 * 365 / 220 = 1.66).  This error I think comes from this line: https://github.com/UoMResearchIT/CapX/blob/dev/PPMTool/Data/Entities/SubTask.cs#L274, at which an extra day is being added in case the start and end date are the same day.  I think that the calculation above also including a Ceiling makes sure that never actually happens, since GetNumberOfCalendarDays must always be 1 or more, so estimatedEndDate = StartDate.AddDays will always be one day more than StartDate, so the adding of 1 here is not necessary.

In contrast to the above, a Fixed Duration project of 3 days duration at 1 FTE is 2 billable days = 14 hours of work.  I think the billable days here is correct.  

A note of proof of "not quite rightness" here is that if you put in some values in "Fixed Work" and press "Update" then switch to "Fixed Duration" and click "Update" without changing anything, the number of days / billable days will increase.  Switch back to "Fixed Work" and "Update" again and it again increases.  Repeat this and it will keep going up and up!  I would expect this to be stable.

**Comment by aharwood2** [comment]
I'll have to investigate further. At first glance, `EndDate.Date.Subtract(StartDate.Date).TotalDays` should never be a fraction of a day since the time component is zero. `TotalDays` as a property is a double but wrapping this in `(int)Math.Round(...)` should be a straight conversion from say 2.0 to 2. There shouldn't be any rounding error at all. All the generation of partial days I picked up i.e.
https://github.com/UoMResearchIT/CapX/blob/767e5c1ad0800771900c0f51fddf293410dfdab3/PPMTool/Data/Entities/SubTask.cs#L270
https://github.com/UoMResearchIT/CapX/blob/767e5c1ad0800771900c0f51fddf293410dfdab3/PPMTool/Data/Entities/SubTask.cs#L285
https://github.com/UoMResearchIT/CapX/blob/767e5c1ad0800771900c0f51fddf293410dfdab3/PPMTool/Data/Entities/SubTask.cs#L297
https://github.com/UoMResearchIT/CapX/blob/767e5c1ad0800771900c0f51fddf293410dfdab3/PPMTool/Data/Entities/SubTask.cs#L307

and made sure they were wrapped in `(int)Math.Ceiling(...)` as per the suggestion. I'll see if I can work out where the issue is coming from. In terms of the test of swapping between Fixed Work and Fixed Duration, I guess that use of ceiling might make this worse e.g.
https://github.com/UoMResearchIT/CapX/blob/767e5c1ad0800771900c0f51fddf293410dfdab3/PPMTool/Data/Entities/SubTask.cs#L285
I wonder now if it was stable before I made them ceilings.

**Comment by aharwood2** [comment]
The process is as follows:
Fixed Work -> Work = 7 -> Billable Days = 1 -> Calendar Days = 1.65 Ceiling 2 -> End Date = Start + Calendar Days -1 -> Fixed Duration -> End Date = Start - Calendar Days + 1 -> Calendar Days = 2 -> Billable Days = 1.2 Ceiling 2 -> Work = 14.

So the use of Ceiling over Round is what makes this unstable!

**Comment by rowleya** [comment]
So I think the functions that are involved here are UpdateDuraion, when there is Fixed Work and UpdateWork when there is Fixed Duration.

In UpdateDuration:
 - DurationBillableDays = (int) Math.Ceiling(7 / 7) = 1
 - GetNumberOfCalendarDays(1) = (int) Math.Ceiling(1 / 220f * 365f) =  (int) Math.Ceiling(1.66) = 2
 - var estimatedEndDate = StartDate.AddDays(2)
 - DurationDays = (int) Math.Round(StartDate.AddDays(2).Date.Subtract(StartDate.Date).TotalDays) + 1 = (int) Math.Round(2) + 1 = 3
   - I believe this should be 2, not 3, so I think Ceiling is correct here.  I also note that Round would result in the same thing.  Both are wrong when the +1 is in place.

In UpdateWork:
 - var endDate = StartDate.AddDays(2)
 - var calendarDays = StartDate.AddDays(2).Date.Subtract(startDate.Date).Days = 2
 - DurationBillableDays = (int) Math.Ceiling((2 / 365f) * 220f) = (int) Math.Ceiling(1.2) = 2
   - This does look wrong also, since above DurationBillableDays = 1.  Maybe that means it should be Math.Floor in this case?  I agree that Math.Round might also be correct, but need to try with something that rounds up to be sure.

Lets try with something where BillableDays rounds up from Calendar days instead of down and see if it still breaks (remember Round is the same as Ceiling in this case):
- UpdateWork with 3 Calendar Days:
  - var endDate = StartDate.AddDays(3)
  - var calendarDays = StartDate.AddDays(3).Date.Subtrace(startDate.Date).Day = 3
  - DurationBillableDays = (int) Math.Ceiling((3 / 365f) * 220f) =  (int) Math.Ceiling(1.8) = 2 (= Math.Round(1.8))
  - Work = 2 * 7 = 14
- UpdateDuration with Work = 14
  - DurationBillableDays = (int) Math.Ceiling(14 / 7) = 2
  - GetNumberOfCalendarDays(2) = (int) Math.Ceiling(2 / 220f * 365f) =  (int) Math.Ceiling(3.32) = 4
  - var estimatedEndDate = StartDate.AddDays(4)
  - DurationDays = (int) Math.Round(StartDate.AddDays(4).Date.Subtract(StartDate.Date).TotalDays) + 1 = (int) Math.Round(4) + 1 = 5
    - Though this = 4 if the +1 is removed.  Note if we used Math.Round above this would be 4 with the +1 or 3 without.  So the +1 is still in doubt!

OK lets try with floor instead:
- UpdateWork with 3 Calendar Days:
  - var endDate = StartDate.AddDays(3)
  - var calendarDays = StartDate.AddDays(3).Date.Subtrace(startDate.Date).Day = 3
  - DurationBillableDays = (int) Math.Ceiling((3 / 365f) * 220f) =  (int) **Math.Floor**(1.8) = 1
  - Work = 1 * 7 = 7
- UpdateDuration with Work = 7
  - DurationBillableDays = (int) Math.Ceiling(7 / 7) = 1
  - GetNumberOfCalendarDays(1) = (int) Math.Ceiling(1 / 220f * 365f) =  (int) Math.Ceiling(1.66) = 2
  - var estimatedEndDate = StartDate.AddDays(2)
  - DurationDays = (int) Math.Round(StartDate.AddDays(2).Date.Subtract(StartDate.Date).TotalDays) + 1 = (int) Math.Round(2) + 1 = 3

Hmm OK, that makes me wonder if the +1 **is** required since it does lead back to stability! 

Looking at this, I think that some of the problem now is that the "End Date" is a date and not a DateTime (which I think you might have changed at some point in the past) i.e. because we eliminate the fractions too early.  The problem is that in calculating a project duration in days, the amount of work possible might not be an integer, and similarly when the work hours is an integer, the project duration in days might not be.  It therefore makes sense to do rounding / ceiling / floor as late as possble i.e. only when you have done the rest of the calculations.

So lets try it!
 - UpdateDuration with 7 hours work:
   - DurationBillableDays = 7 / 7 = 1
   - GetNumberOfCalendarDays(1) = 1 / 220f * 365f = 1.66
   - var estimatedEndDate = StartDate.AddDays(1.66)
   - DurationDays = StartDate.AddDays(1.66).Date.Subtract(StartDate.Date).TotalDays = 1.66
 - UpdateWork with 1.66 days duration
   - var endDate = StartDate.AddDays(1.66)
   - var calendarDays = StartDate.AddDays(1.66).Date.Subtract(startDate.Date).Days = 1.66
   - DurationBillableDays = (1.66 / 365f) * 220f = 1
 
Yep, that all works out!  Lets try the other way with 3 days duration:
 - UpdateWork with 3 days duration
   - var endDate = StartDate.AddDays(3)
   - var calendarDays = StartDate.AddDays(3).Date.Subtract(startDate.Date).Days = 3
   - DurationBillableDays = (3 / 365f) * 220f = 1.8
   - Work = 1.8 * 7 = 12.66
- UpdateDuration with 12.66 hours work:
   - DurationBillableDays = 12.66 / 7 = 1.8
   - GetNumberOfCalendarDays(1.8) = 1.8 / 220f * 365f = 3
   - var estimatedEndDate = StartDate.AddDays(3)
   - DurationDays = StartDate.AddDays(3).Date.Subtract(StartDate.Date).TotalDays = 3

Once again, success!

OK, so now I am going to state that I think that the amount of work we do on a project should be an integer number of hours  but that the duration of a project in days doesn't need to be (it can be displayed as such, but the actual value internally doesn't need to be).  If we take that, we should do something with the billable days and work, but not the duration in days.  I propose that for Billable Days we use Ceiling, and for Work we use Floor, though Work should be calculated from BillableDays before we do the Ceiling (as otherwise we get the wrong values above).  The reason for this is that you won't be managing the project for a fraction of a day - any fraction should be rounded up.  Equally the amount of work you can do in a fixed number of days can't increase, as otherwise you add a day!

OK, lets try that with the 3 day example again:
 - UpdateWork with 3 days duration
   - var endDate = StartDate.AddDays(3)
   - var calendarDays = StartDate.AddDays(3).Date.Subtract(startDate.Date).Days = 3
   - DurationBillableDays = (3 / 365f) * 220f = 1.8
   - Work = (int) Math.Floor(1.8 * 7) = 12
   - DurationBillableDays = (int) Math.Ceiling(1.8) = 2
- UpdateDuration with 12 hours work:
   - DurationBillableDays = 12 / 7 = 1.7
   - GetNumberOfCalendarDays(1.7) = 1.7 / 220f * 365f = 2.8
   - var estimatedEndDate = StartDate.AddDays(2.8)
   - DurationDays = StartDate.AddDays(3).Date.Subtract(StartDate.Date).TotalDays = 2.8

So that looks like you can Ceiling DurationDays if you want to, as that will lead back to 3!  If we do that, lets try in reverse with 7 hours again:
 - UpdateDuration with 7 hours work:
   - DurationBillableDays = 7 / 7 = 1
   - GetNumberOfCalendarDays(1) = 1 / 220f * 365f = 1.66
   - var estimatedEndDate = StartDate.AddDays(1.66)
   - DurationDays = (int) Math.Ceiling(StartDate.AddDays(3).Date.Subtract(StartDate.Date).TotalDays) = 2
 - UpdateWork with 2 days:
   - var endDate = StartDate.AddDays(2)
   - var calendarDays = StartDate.AddDays(2).Date.Subtract(startDate.Date).Days = 2
   - DurationBillableDays = (2 / 365f) * 220f = 1.2
   - Work = (int) Math.Floor(1.2 * 7) = 8
   - DurationBillableDays = (int) Math.Ceiling(1.2) = 2

OK, so not perfect, but pretty close!  I also don't think it is wrong; in those 2 days that we rounded up from before, we found that we can actually do 8 hours of work.  But doing 7 hours of work also takes 2 days.  I won't do the calculations explicitly, but note that 8 hours does indeed result in 2 days again if reversed, so I think think this is correct, and also has valid reasons for existence as described above.

**Comment by rowleya** [comment]
I think I have made the above changes in #412

**Comment by aharwood2** [comment]
[This commit](https://github.com/UoMResearchIT/CapX/commit/231a86b691ca11c3b06936f2cb8662e175b42e75) probably gets it somewhere near? The "instability" I think is designed behaviour since by switching between fixed work and fixed duration you are essentially changing the outputs to input where the outputs were fractions rounded up. If we then use the rounded up values as inputs you would expect the original inputs (now outputs) to also be larger as a result.

Ultimately, as I have it now, 7 hours fixed work is 1 billable and 2 calendar which I think is what you said was the main error. 2 calendar days is 2 billable days = 14 hours. Although that is not "stable" it is correct if we assume that any fraction of a day should be rounded up to a full day:

7 hours = 7 / 7 = 1 billable days = 1 / 220 * 365 = 1.66 calendar days  => 2
2 calendar days = 2 / 365 * 220 = 1.21 billable days => 2 = 2 * 7 = 14 hours work.

**Comment by aharwood2** [comment]
Sorry -- your message updated on my screen after I'd posted mind. Will read your stuff now.

**Comment by rowleya** [comment]
Sorry it is a bit long winded - it is a series of experiments I tried as I wrote it!  I created the PR which should do what it concludes in the end, which is not far off what you did in the commit, but still different I think.

**Comment by aharwood2** [comment]
Thanks Andrew -- appreciate your effort on this!
