### ISSUE TITLE
Finished Projects Capacity on CapX

### ISSUE THREAD

**Issue by amangoel185** [UoMResearchIT/CapX#381]
[Via [Teams thread](https://teams.microsoft.com/l/message/19:09874bfb6c3c4209838a5dc3632ea72f@thread.tacv2/1721997967101?tenantId=c152cb07-614e-4abb-818a-f035cfa91a77&groupId=22c918a5-7504-4d24-9623-d592a54bc139&parentMessageId=1721997967101&teamName=Research%20IT&channelName=RSE%20Team&createdTime=1721997967101)]

Is there a way to look at finished projects in the Capacity graph on CapX? There's a switch for "Include Finished?" under the main Projects tab, but can't see anything similar under Capacity.
 
Zooming out shows me the timeline from 2023, but still doesn't show the finished projects, is that by design?

**Comment by aharwood2** [comment]
The capacity chart filters out finished and cancelled projects to avoid an forever growing number of rows on the chart. You can find out details about a finished project by finding it in the data grid on the Projects page and then clicking the "info" button at the end of the row to view the details of the project. The Gantt on that page will show you the assignment info you are after I think.

**Comment by aharwood2** [comment]
I can add a switch to show finished project info on the capacity chart as well but I worry that the chart would just become taller and taller over time with the switch on as the DB will hold a record of every project you worked on ever. Can you live without it given the above or would you still like it?

**Comment by amangoel185** [comment]
The switch would be nice to have, but since we can look at the individual project information, it isn't a big requirement! Happy to close the issue if we'd rather skip it.
