### ISSUE TITLE
Can't split task for project that I own

### ISSUE THREAD

**Issue by douglowe** [UoMResearchIT/CapX#389]
I have tried to use the task splitting tool for project RTP-224, and am getting the error `Only the project manager or a superuser is authorised to edit project details!`, even though I am listed as the PM for that project. This is for CapX v1.10.4.

**Comment by aharwood2** [comment]
Thanks Doug -- will investigate! Will aim for a hotfix in the next week.

**Comment by aharwood2** [comment]
OK, replicated and fixed.
