### ISSUE TITLE
Search for project: Make it case insensitive

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#39]
Current search for a project name is case sensitive. Would it be better to make it case insensitive?

**Comment by aharwood2** [comment]
Possible that this has been addressed already when I improved the search capability but will test as it is a quick fix if not.

**Comment by aharwood2** [comment]
OK done. Turns our that if you use SQL Server, it is case insensitive by default. If you use SQLite (which this does), it is case sensitive by default. Fortunately the Data Grid component exposes a flag to set this so ti was easy in the end.
