### ISSUE TITLE
Switch between project summary page and detail page

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#40]
It would be very helpful if there are buttons on project summary page and its detail page, so user can easily go to another page when editing info for a project. Currently once data is saved user will be taken back to the project list page.

**Comment by aharwood2** [comment]
What sort of navigation did you have in mind for this? Where would you want to go from the project details page?

**Comment by TheresaTeng** [comment]
I'm not sure if I missed anything and didn't use it properly, but here is what I mean, I'll use project "RTP-20 Decent Work and the City" as an example to explain:

When I'm in project details page https://balex.itservices.manchester.ac.uk/projectdetails/40, if I want to make a change in project info page https://balex.itservices.manchester.ac.uk/addproject/40, I can't go there directly. I'll need to go back to project list page to find my project, then go to project info page to make changes. 

It's the same another way around. If I'm in project info page https://balex.itservices.manchester.ac.uk/addproject/40, and want to go to project details page https://balex.itservices.manchester.ac.uk/projectdetails/40, I also need to go via project list.

If there are buttons on these two pages it will make it much easier for user to switch between project info and details pages.

**Comment by aharwood2** [comment]
Ah yes, I understand. Will add it to the list for the next milestone as it is another easy one.

**Comment by aharwood2** [comment]
OK done this now.
