### ISSUE TITLE
Add demand for App Support and Training

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#408]
App Support and Training are services that have a demand and should be captured in the required demand for PSM. At the moment, it is not. We can have inputs in the reference data for "Service Leadership" or similar to capture this.

**Comment by ianhinder** [comment]
Are app support and training considered a service under PSM? We don't track app support or training engagements in CapX; does it make sense to track demand? Is CapX going to be used to track everything in RSE?

**Comment by aharwood2** [comment]
CapX needs to work out how much capacity each individual has for managing projects. The simplest way to do this is to take the value of PSM from their workload model. However, the graphs were out because the bits of time used to run the training service and the app support service were being seen as time that could be used to manage projects. This issue simply added in a text box on the data dashboard that allows me to set the required demand for running those services so it is properly represented and we aren't seen as having extra capacity to manage projects that doesn't exist.

So in answer to your questions: 1. Yes, 2. Yes for the reason above but it is just represented as a flat "this is how much time person X needs to run service Y", 3. Maybe :)
