### ISSUE TITLE
Longer info fields

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#41]
Can info fields be made longer? Current length for many text fields seems to be quite short. One needs to scroll to see, say, the full name of a project.

**Comment by aharwood2** [comment]
Do you mean the column width of the data grid? Are there particular columns you would like increasing? It is easy to do so if you let me know I can do it in seconds.

**Comment by TheresaTeng** [comment]
I mean the text fields in various pages:
- Project name and PI name in project info page
- Task name in Task detail page
- Person name in Person page

**Comment by aharwood2** [comment]
Ah OK, you mean the edit forms? Should be easy to sort so will add to the current milestone.

**Comment by aharwood2** [comment]
OK, I've just made all these 100% instead.
