### ISSUE TITLE
Filter available projects view by start and end date

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#422]
I think it would be a good feature to be able to filter the available projects by a time period.

It needs to be a bit fuzzy I suppose which would make it more complicated.

e.g. if someone currently doesn't have a project between 01/01/2025 and 30/06/2025 then they could look at the page, enter the start and end date and see which project start then (perhaps +/- 2 months). 

We should allow an empty end date in the search criteria for those who have nothing listed in the future.

The search result could perhaps indicate whether their available time would cover the entirety of the project or just a portion.

I suppose an even more complex solution would do this automatically on a button click, i.e. check their availability for them so they don't have to type anything in the search.

**Comment by aharwood2** [comment]
- [x] Add date input to the page
- [x] Implement filtering and clear filter button
- [x] Automatically group by status with active at the top but still sorted by unmet demand
