### ISSUE TITLE
Available projects view unmet demand dates

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#425]
In the available projects view the dates under the 'unmet demand' label appear to just show the start and end date of the project itself. However I think it would be nicer to show the dates for the unmet demand to give a better idea when someone is needed.

An example is RTP-59 AINOSTICS. It has dates as being 'Now - 24/07/2026' but in reality the unmet demand is actually from end of January 2025, not 'now'.

**Comment by aharwood2** [comment]
I think I will try to keep this simple and just state the window in which there are tasks with unmet demand. It could be that the demand is unmet, then met then unmet again with varying values. That would require a full blown bunch of processing on the tasks the likes of which we do for the capacity graphs which would be too heavy I think. I may will just state there is a maximum of X FTE of unmet demand in the period Y to Z and leave it at that?

**Comment by aharwood2** [comment]
Ties into how useful #422 would be as well but I guess the idea is that it provides a guide not necessarily a precise indicator.

**Comment by aharwood2** [comment]
Addressed now I think?

![Image](https://github.com/user-attachments/assets/9322e2ff-cb67-4051-80e7-f955efb2d1e5)
