### ISSUE TITLE
Project management capacity view

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#427]
It might be useful to have a way to see project manager capacity, especially when a PM needs to offload projects, or if a PM is overburdened.

Maybe a table with the PM on the vertical axis and the number of projects in different states on the horizontal axis, as well as the fraction of the PM's active project capacity that is currently utilised, which could be colour coded so you can easily see over- or under-capacity.

e.g. something like this:

<img width="443" alt="image" src="https://github.com/user-attachments/assets/fffb33c7-21e1-4f88-8ac5-768857d9ad16">

**Comment by rowleya** [comment]
See also #241

**Comment by aharwood2** [comment]
Duplicate of #241

**Comment by ianhinder** [comment]
I did read #241, but I felt that that was more about long-term capacity planning, and the solution to that was much more involved than what I am proposing here. That issue also said
> Suggesting a PM based on who has capacity would probably fall under a different feature as this isn't simple since projects can be passed from one person to another so there is more "capacity" than we think if we are willing to pass projects round more frequently. Needs some thought.

I think the current Issue is the mentioned "different feature", and is much simpler to implement, whereas #241 is more involved. This issue would be a simple snapshot of the current state of things, allowing you to easily see who can swap projects etc.

If you think that this functionality would be included in #241 and that this will be implemented, then I'm happy for this to be closed, but it wasn't clear to me that that was the case.
