### ISSUE TITLE
Retain predecessor in task page

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#43]
Predecessor set for a task doesn’t seem to be retained in task editing page. If I set a predecessor, save it, and later on reopen the task page, the value isn't there.

**Comment by aharwood2** [comment]
This just looks like I forgot to set the "selected" property when editing. Should be a quick fix. Will do it for the next update.

**Comment by aharwood2** [comment]
Fixed in next version.
