### ISSUE TITLE
Way to see current Confirmed Unmet demand projects

### ISSUE THREAD

**Issue by rowleya** [UoMResearchIT/CapX#437]
It would be useful to see a list of projects / tasks that equate to the Confirmed Unmet demand "today" on the Data Dashboard.  At present it is hard to see what adds up to the total there; we can see that there is confirmed unmet demand, but can't tell who might work on that as of today if someone is available (e.g. new starters in this case).

I noted also that the "show finished separately" off gives slightly different results to the above count, and so might list tasks that have already finished.  This would be fine as it conforms to the request, but also suggests that start / end dates could be useful on the resulting display of the above.  I might also suggest then that this is turned on by default, and when on, doesn't list finished tasks in the above (or lists them separately as the option suggests it should).

**Comment by aharwood2** [comment]
This should be just the active or funded projects with unmet demand as listed on the Available Projects page. I'm not sure there is much value in representing it a different way somewhere else.

**Comment by rowleya** [comment]
I would like that to be the case, but the Available Projects page appears to not match the unmet demand - there is far more unmet demand in Available Project than there is on the graph it seems.  That is probably because it is hard to see there what the task starts/ends are, so it doesn't end up being of much use since we can't tell if the task is available now, in the next few weeks or in 2 years.  That then doesn't help to match people up as they join.

**Comment by aharwood2** [comment]
OK, the newer version of CapX that is not yet out improves this but there are some things I can do. The data dashboard sums up the tasks on a week by week basis. The available projects page shows the max amount of unmet demand for a project within a particular window so the calculation is not quite the same.
- [x] Show max and min unmet demand in the period selected on the available projects page not just max.
- [x] Add an original demand alongside the current demand so we do get some history and set SQL script to default the current demand to the original demand.
- [x] Allow current demand of a task to be zero as I think there is a warning at the moment to prevent this but ensure that original demand is not zero.
- [x] Check where the Demand parameters is used to see if we need to modify it -- I suspect that the original demand might be only useful on the data dashboard to indicate where demand disappeared.

**Comment by aharwood2** [comment]
Improved the information on the available projects page so it shows the range of demand in the window selected: ![Image](https://github.com/user-attachments/assets/e1b72bc9-3244-4f14-a14e-83230cdb5b3d)

**Comment by aharwood2** [comment]
The combination of this plus the "window" selection should make this board more useful for seeing what is available right now and to what extent.

**Comment by rowleya** [comment]
Sounds good - thanks!
