### ISSUE TITLE
Minimum acceptable value for person

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#44]
Maintenance task usually is a few days a year for most WADS projects, the system won't accept it.

**Comment by aharwood2** [comment]
When you say it won't accept it, how are you adding the task? If you know the number of hours then you can make it fixed work. If you know the percentage you want the person on it then it can be fixed units. It is possible that you can't put the required decimal places in to achieve what you want but I have fixed this already in the next version so will put on hold for now until I can verify.

**Comment by TheresaTeng** [comment]
Use "RTP-22 Politics of Equality at Work" as example:

The task for maintenance would be 3 days per year for 3 years. When I tried to add resource to it, the minimum percentage I can use is 10%, but 3 days per year is well below 10%. So at the moment I put Josh on the task as 10%, although it's not correct.

**Comment by aharwood2** [comment]
Right, got it. Yes, this will be fixed automatically in the next version as I've allowed you to put in 1% increments.
