### ISSUE TITLE
Start date not updated on "update" button when end date changed in fixed duration task

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#440]
The last task in RTP-123 has a fixed duration, and a fixed end date. When I change the end date and click "Update", I expected the faded out start date to update to reflect the changed time period. It does not.

<img width="942" alt="image" src="https://github.com/user-attachments/assets/8a72f61b-b568-4a48-ab5b-a0c1c53f25db">

**Comment by aharwood2** [comment]
CapX only implements forward scheduling. See #244 for the task to implement reverse scheduling.
