### ISSUE TITLE
Sort RSE names in task page

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#45]
It would be useful to show the RSE names in alphabetic order. There are a lot more names now and they are listed based on the time they are added in, not easy to find a person.

**Comment by aharwood2** [comment]
Yes of course. Easy one to sort so will do so in the next milestone.

**Comment by mawds** [comment]
Pls ignore; I was looking at the wrong page

~~You can do this already, by first name (though it doesn't default to it) - there's a sort icon on each column:~~

![image](https://user-images.githubusercontent.com/12030124/195806898-55abb2a3-e227-4cd2-b9d2-ee880c075fe6.png)

**Comment by aharwood2** [comment]
OK done. Will be in next version.
