### ISSUE TITLE
Calculation of the schedule

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#46]
Documentation on how a schedule is calculated would be useful, for all sorts of tasks.

**Comment by aharwood2** [comment]
Yes, this can be added to the readme. I think just undertstanding the concepts of fixed work/duration/units can be talked about as if you don't have much project management / estimating and scheduling training then these might be confusing. Will have a look at this for the following milestone but happy to explain in person until then.

**Comment by aharwood2** [comment]
I think I have achieved this with the modifications to the README recently but please re-open if it is not sufficient.
