### ISSUE TITLE
Capacity planner to show completed projects too

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#463]
At the moment the capacity planner only shows projects that aren't finished. For PSM purposes this is fine, but as a line manager I'd like to be able to look back at the projects that my reports have been allocated to in the past as well.

There might be other ways of doing this other than the already very busy capacity planner, but it would be a useful feature when reviewing the year at PDR time.

**Comment by aharwood2** [comment]
Sure -- just needs a switch adding next to the ones on unfunded and leavers I think and the filter method updating.

**Comment by aharwood2** [comment]
This is now on the dev system (or will be in a few minutes when the deployment pipeline has run) so if you need the info now then you can get it from there instead of waiting for the next prod release.
