### ISSUE TITLE
Truncated fields even when there is plenty of screen space

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#466]
On a 14 inch laptop screen, with CapX maximised, at 100% browser zoom (macOS Safari), the combination of font size and padding/margin in the tables causes truncation of the data fields. 

![image](https://github.com/user-attachments/assets/71caaa7e-3e81-4bf0-9ee2-1db97ee9a5a0)

With this font size, the table will have to be scrolled anyway, so I think it's better to be able to see the full data and column headings without having to manually resize the columns.

In order to see the dates, I have to zoom out to the maximum.

Perhaps the solution here is to reduce the padding a bit in the table?

**Comment by rowleya** [comment]
Equally, there is a scroll bar here and yet the data is truncated... should the minimum width of each column be such that all the data is visible anyway if it is going to scroll as well?

**Comment by ianhinder** [comment]
I think it would make sense to truncate fields if they were very long, but not if they are something short like a date or a number.

**Comment by aharwood2** [comment]
The way this control works is you can specify the default width a of a column or specify the width of each column individually which override the default width. Fixing this issue is literally a case of manually messing with the numbers until you get the level of visibility you want. Sadly there is no "auto width" behaviour exposed.

**Comment by rowleya** [comment]
I can see that all the columns are set to 100px explicitly.  I wonder if using the "rem" units would help, and using different values for different fields might help, as then dates might fit better, and would scale with zoom level (as I understand it)?

**Comment by aharwood2** [comment]
Just a note to self to not attempt to auto-width via a CSS override :) https://forum.radzen.com/t/datagrid-with-horizontal-scrollbar-and-auto-width-for-columns/12771/6

**Comment by aharwood2** [comment]
Made some manual adjustments which I guess will do OK for now such is the limitation of the component being used. Any other "small-screen" type issues are welcome as these are easy adjustments to make.

**Comment by ianhinder** [comment]
Small screen..... I remember when 640x480 was considered good!
