### ISSUE TITLE
Error shows when changing the value in 'Current Demand' to 0

### ISSUE THREAD

**Issue by jiawu-2** [UoMResearchIT/CapX#475]
When editing the field 'Current Demand (FTE)' in existing task to 0, an error message is shown :'Task configuration is invalid: Demand for a task must be greater than zero!'

**Comment by aharwood2** [comment]
Easy fix:
```
if (TaskModel.Demand <= 0)
{
    error = "Demand for a task must be greater than zero!";
    IsValid = false;
}
```

just needs changing to 
```
if (TaskModel.OriginalDemand <= 0)
{
    error = "Original demand for a task must be greater than zero!";
    IsValid = false;
}
```

Will do shortly and will be patched tomorrow :)
