### ISSUE TITLE
Cannot add more than one unallocated person

### ISSUE THREAD

**Issue by AnjaLeBlanc** [UoMResearchIT/CapX#48]
Try to add tasks to a project.
I need to allocate two so far unnamed people to the task.
CapX only allows me to allocate up to 100% i.e one person.

**Comment by aharwood2** [comment]
Ah right, as in you need to be able to allocate the Unallocated person 200%? Should be a straightforward change. Will do it this milestone.

**Comment by aharwood2** [comment]
I suppose another way you could do this would be to have two tasks and allocate someone at 100% to each. Not sure it that would be better actaully but I'll bump up the maximum to 1000% for now :)
