### ISSUE TITLE
UI for adding absences isn't working properly 

### ISSUE THREAD

**Issue by AnnAnnFryingPan** [UoMResearchIT/CapX#489]
When adding a sickness absence (just done for Chris and also belatedly for Adina), it wouldn't let me add the dates at first, so I had to add a row without dates, then go back in to edit the dates.

**Comment by aharwood2** [comment]
Can you do a screen record of what you are doing? I'm not sure I follow your description.

**Comment by AnnAnnFryingPan** [comment]
Actually, now I've had another play around, I think I'd got mixed up between the adding new absence row and the search row. They both look very similar, and there is no 'search' title on the search row.
ie I thought I was adding a row but I was editing the search row.
