### ISSUE TITLE
View Capacity for all the people I line manage

### ISSUE THREAD

**Issue by SJaffa** [UoMResearchIT/CapX#508]
Would be a useful shortcut to checking how my line reports are allocated to quickly see their capacity graphs. Not hugely needed, just a thought that this might be nice.

- [x] Add line manager relationship in DB #562 
- [x] Add line manager setting to data grid and UI
- [x] Restrict editing of person entries to SU, LM and the person themselves
- [x] Add dropdown to capacity and appropriate logic to filter

**Comment by aharwood2** [comment]
Would it suffice to have a button "Show my Staff" that just selects your staff automatically from the dropdown?
