### ISSUE TITLE
See the current page in the tab title so I can tell which tab is which

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#519]
In Safari on macOS, if I have multiple CapX tabs open, the tab titles all say "CapX":
<img width="911" alt="image" src="https://github.com/user-attachments/assets/5bf969be-9912-4ee6-8760-9d361263958b">

In GitHub, if I have multiple tabs open, each tab title says the page that is open:
<img width="572" alt="image" src="https://github.com/user-attachments/assets/829fc365-bccb-437e-a86e-a0efc9e823bf">

Is it possible to get CapX to do the same? I would like to know which is my "People" tab, which is "Capacity", etc.

A quick search yielded [this](https://stackoverflow.com/questions/77896632/how-can-i-set-the-page-title-the-browser-tab-text-in-blazor) which says you should set `PageTitle`.

**Comment by aharwood2** [comment]
Blazor is typically an SPA so will have to dig in to see how this will work. I doubt it will be a problem though as it seems like a pretty fundamental use-case.

**Comment by ianhinder** [comment]
Probably whatever routing configuration allows the page address to seem to change will also have a way to set the title.
