### ISSUE TITLE
Mouseover on bars on Capacity screen doesn't show detailed start and end dates on MacOS/Safari

### ISSUE THREAD

**Issue by cjfullerton** [UoMResearchIT/CapX#522]

**Comment by ianhinder** [comment]
For me at least, the mouseover doesn't appear at all on Safari.

**Comment by aharwood2** [comment]
Could you see if the events work on the chart on this page: https://apexcharts.com/docs/responsive/
and also this page: https://apexcharts.github.io/Blazor-ApexCharts/
Trying to figure out which library might be the cause.

**Comment by aharwood2** [comment]
Also, is it just the Capacity page or is it any graph -- i.e. ones on the Data Dashboard too.

**Comment by aharwood2** [comment]
And what versions of Safari are you using?

**Comment by cjfullerton** [comment]
> Could you see if the events work on the chart on this page: https://apexcharts.com/docs/responsive/ and also this page: https://apexcharts.github.io/Blazor-ApexCharts/ Trying to figure out which library might be the cause.

Mouseover pop-ups working for me on these pages.

**Comment by cjfullerton** [comment]
> And what versions of Safari are you using?

18.0.1

**Comment by cjfullerton** [comment]
> Also, is it just the Capacity page or is it any graph -- i.e. ones on the Data Dashboard too.

Mouseovers work on the Data Dashboard and on the burn-up chart on project pages, but not on the bars representing tasks on the project schedule plot.

Also, I can no longer click on bars on an individual RSEs capacity page and end up at the project page for that bar (I think this used to be a thing?).

**Comment by aharwood2** [comment]
It sounds like it is limited to just the Gantt style charts. I can take a look and see if there is anything particular about the tooltips on those charts. It is more likely to be a bug in the wrapper or the JS library I suspect.

**Comment by aharwood2** [comment]
I did find a SO post of someone reporting a few days ago an issue with chart events not firing on Safari but the post has been deleted. I can't find anything on the ApexCharts.js or Blazor-ApexCharts GitHub repos. I best switch over to mac and verify that the events are not firing on Safari and if I can file a bug report, I might be able to get some advice on generally why certain events might not be fired on certain browser versions. I would have thought these kind of things would be standardised across browsers, well at least for common events.

**Comment by aharwood2** [comment]
I've just built and run on my Macbook using Safari Version 16.5 (18615.2.9.11.4) and the tooltips work but the pounds signs don't show up properly. Not sure this helps us much in the current situation but an observation all the same.

**Comment by ianhinder** [comment]
Safari 18.0.1 is the version I have where it doesn't work. Can't check the new release as CapX is currently down. However, mouseovers work on balextest! So hopefully this has been fixed with the new theme? My guess is that it was related to the scroll/zoom issue?

**Comment by aharwood2** [comment]
> Safari 18.0.1 is the version I have where it doesn't work. Can't check the new release as CapX is currently down. However, mouseovers work on balextest! So hopefully this has been fixed with the new theme? My guess is that it was related to the scroll/zoom issue?

CapX is back up. Could you check it works again in production?

**Comment by ianhinder** [comment]
Works for me in production. Thanks!

**Comment by aharwood2** [comment]
Great! @cjfullerton is it OK for you too?

**Comment by cjfullerton** [comment]
All good for me too.
