### ISSUE TITLE
Leadership charge calculation might be wrong

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#531]
I thought I understood the leadership charge, but I don't understand where the CapX number is coming from, so one of us is wrong... For RTP-295, the project duration is 143 days. So leadership charge should be 0.05 x 143/365 x £64,797.29 = £1269. But CapX is showing £727. Any ideas? Code is [here](https://github.com/UoMResearchIT/CapX/blob/8bce7b074ffb01803b736e83b17d55b79642516d/PPMTool/Data/Entities/Project.cs#L331).

**Comment by aharwood2** [comment]
The revised end date for the project is calculated before the leadership costs are then calculated but not actually set until after! Swapping these around should sort it out.
