### ISSUE TITLE
Poll working group regarding tech stack/approach

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#537]
Initial working group meeting was held on 01/11/24. 

4 main options discussed/proposed for the direction to take for development work. Agreed to poll the group to get initial data on preferred way forward.

- CapX integrated
- "Free-for-all" front-end development against a CapX API (to be coded)
- Use/adapt existing "off-the-shelf" (Open Source) product
- New system from scratch using sporadically available RSE 'voluntary' resources

**Comment by PhilBradbury** [comment]
[07/11/24] Results for 10/11 members of the group are:

![Image](https://github.com/user-attachments/assets/c681eec0-f76b-4ec5-b562-47b9a593a5b6)

**Comment by ianhinder** [comment]
The problem with having it fully integrated into CapX was that the rest of ITS might in future want to make use of it, and so I thought the preference was to have it standalone.

An existing open source project, hosted by us, configured to our needs, would seem to be the prudent choice here; at the very least we should prove that that is not feasible before rolling our own.

Probably we should make a list of hard requirements and then evaluate existing solutions against them.

**Comment by PhilBradbury** [comment]
That was definitely something that was taken into consideration. It should be possible to open up just this component to "non-RSEs" in the University (albeit potentially a bit faffy) though. We decided that the advantage/headstart offered by having authentication/authorisation, project data, project codes, people etc. already built in to CapX is huge though, and far outweighs the downsides.

**Comment by ianhinder** [comment]
But if it was opened up to a wider community, would we then have to incorporate all that for them as well? I guess this is a theoretical future cost, vs a real saving now.  OK, sounds good!

I still think that using an open source option where the actual code was already written and maintained would be the best approach, unless there is a good reason not to. Adding the data about users and projects, and integrating it with authentication, is much less work than developing the app from scratch and maintaining it.
