### ISSUE TITLE
Model the data structure required for a timesheet

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#538]
A timesheet needs to be 'owned' by a single person and be able to hold the data for the number of hours (and partial hours down to the 1/4 hour) per day spent on an activity/task code during a week. 

It will need to be able to hold data for that user for multiple codes over multiple days. 

It will need a status (New / Under Review / Rejected / Approved / ... ) so it can be tracked through its lifecycle and be editible by the user until it has been approved.

**Comment by aharwood2** [comment]
Another thing occurred to me about this. Projects consist of Subtasks and the actuals for those subtasks are aggregated from the bookings. We will need the option of associating a timesheet task with a Subtask. In an ideal world, these would perhaps be the same model but there are cases where they shouldn't be so separate models is probably OK. That means that the Subtask model is going to need to have a one-to-one relationship with a timesheet task too in order for the actuals to be populated automatically.
