### ISSUE TITLE
Predecessor handling during splitting of tasks / split tasks broken

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#545]
When splitting a task, dependencies should be attached to the second task, not remain with the first part.

**Comment by aharwood2** [comment]
This is really a bug as it should just do this I think. I also wonder whether the split tasks should have a dependency with the appropriate lag?

**Comment by ianhinder** [comment]
When I used the feature (for the first time) today, I wanted to both split and introduce a gap. My feeling is that the splitting of tasks can be done in so many different ways, depending on what you want, that it might be best to keep the feature as "dumb" as possible.

There is a lot of UI for specifying the details of the child tasks (the ones created by the split). Wouldn't it be simpler to just say "split this task at this date", and then let the user modify the resulting tasks if they want to change them?

**Comment by aharwood2** [comment]
> When I used the feature (for the first time) today, I wanted to both split and introduce a gap. My feeling is that the splitting of tasks can be done in so many different ways, depending on what you want, that it might be best to keep the feature as "dumb" as possible.
> 
> There is a lot of UI for specifying the details of the child tasks (the ones created by the split). Wouldn't it be simpler to just say "split this task at this date", and then let the user modify the resulting tasks if they want to change them?

We could, but by presenting the views side by side it was intended to save "post-splitting massaging". I'm not fussed really though. If people are happier with a less complex solution then I can "downgrade" the current feature to provide it. What do others think? Probably best handled on a separate issue if we do as this issue is specifically about the broken handling of predecessors during a split.

**Comment by ianhinder** [comment]
In the current implementation, if I leave all the settings in the new tasks untouched after initiating the split, do I get the same effect; i.e. the task is just split at the given date with everything else maintained? So I can then go into the more familiar UI for modifying the second task if needed? I guess it would be unusual to need to modify the first task.

**Comment by aharwood2** [comment]
Yes, it does. The simplest thing you can do is click the split button, choose the date you want the second task to start and then click "split task" and then "update and save" and you are returned to the details page with the tasks divided. You can then just edit the tasks afterwards as required.

**Comment by aharwood2** [comment]
Discovered an issue with this feature having messed around with it. My current tests are showing that the new task is not being saved properly so I'll need to solve that before this feature can be completed.

**Comment by aharwood2** [comment]
I've been messing with this and have the predecessor linking to the original task OK but not the successors. Sometimes the new tasks are added to the DB without a project reference which is strange and sometimes they can have predecessors of invalid tasks so it is all a bit of a mess somehow. Might be easier to bin this feature for a simple pop-up and then sort the tasks out in edit later.

**Comment by aharwood2** [comment]
Scenarios to test:
1. Single Task split -- linked to new task
1. Two Tasks Linked, Second Task split - predecessor should be preserved, linked to new task
1. Two Tasks Linked, First Task split - linked to new task, new task should link to second task
1. Three Tasks Linked, Middle Task split - predecessor should be preserved, linked to new task, new task should link to last task

**Comment by aharwood2** [comment]
Testing https://github.com/UoMResearchIT/CapX/commit/75e986d5f501bfcd87bec8977a22fee973b82ac5
1. Works as expected ✅ 
2. Works as expected ✅ 
3. Testing failed:
    - Issue -- as the name of the new task clashes, it requires an edit. If we click Update and Save without resolving the issue, as the first task passes validation it saves to the DB which also saves the project and hence saves the invalid task. ❌ 
    - Issue -- the new task is created but is saved without a project ID. I think this is due to the project meta data firing a project save during the task update. We should move the project meta data update outside the task save so that a task can be saved to the DB but the project is unaffected. ❌ 
    - Issue -- done the above but the task is added still without a project ID. The predecessor linking looks OK. ❌ 
    - Works as expected ✅ 
4. Works as expected ✅

Verified via: https://github.com/UoMResearchIT/CapX/commit/1e80a91e38c3cf93cd19d8f6d3cbedcdefac9e4d
