### ISSUE TITLE
Bug adding assessment to development journey/competencies

### ISSUE THREAD

**Issue by SJaffa** [UoMResearchIT/CapX#564]
When adding an assessment for a competency, if I don't add a description I get an error message "An error has occurred. This application may no longer respond until reloaded" and the page freezes. This seems to happen whether I am marking it as met, partially met or unmet.

This might be a planned restriction that an assessment needs a comment, but it probably shouldn't need one for "unmet" and should give a more user-friendly error message.

**Comment by aharwood2** [comment]
The error message you see is the standard Blazor app has crashed error which means it is unhandled. It is not our error message. I've found the problem with this and fixed it. It was actually crashing while trying to validate the value to check it wasn't empty. Didn't do a check it wasn't null first though!
