### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#568]
- [x] Left alignment in grid on AddTimesheet page (grid heading text, header row text, items)
- [x] Vertical alignment of header text on all columns with data in  them
- [x] Add timesheet entry button : spacing around it

**Comment by aharwood2** [comment]
Fixed the add button spacing via #596

**Comment by PhilBradbury** [comment]
Vertical alignment sorted by centralising text in #626

**Comment by PhilBradbury** [comment]
Fixed the first issue in #615
