### ISSUE TITLE
Remove Update and Discard buttons

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#569]
Remove these buttons. We want a Save for the whole timesheet that will save all entities to the db but leave the page open for the user to continue editing.

**Comment by aharwood2** [comment]
The discard button is there for when a reviewer doesn't want to save their comment or status change. The Update button, saves the changes. Why should they be removed? They serve a purpose.

**Comment by aharwood2** [comment]
I've worked on this as part of #556 so will close this issue as a won't fix since it will be picked up again by your review of the associated PR.
