### ISSUE TITLE
Note link button doesn't work in Safari

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#570]
When I click on the Note link button, to copy a link to a note, I get the following error, when using Safari 18.1.1 on macOS.

> NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

![image](https://github.com/user-attachments/assets/b6f5398f-e998-4046-8aa2-c08790146397)

There was no prompt asking for permission, and nothing in the javascript console. There are no relevant website-specific settings for this; I have allowed popups and disabled content blockers for the site.

It works on Firefox.

**Comment by aharwood2** [comment]
Couple of SO issues related to this:

https://stackoverflow.com/questions/79110228/clipboard-api-notallowederror-in-safari-when-copying-html-in-blazor-application

https://stackoverflow.com/questions/62327358/javascript-clipboard-api-safari-ios-notallowederror-message?rq=2

We run our own JS to copy to the clipboard so it is likely that I just need to update this with whatever Safari now allows.

**Comment by aharwood2** [comment]
I'll roll this out with v1.12 but haven't tested it so be sure to test this on the test system after about 9:45.

**Comment by ianhinder** [comment]
![image](https://github.com/user-attachments/assets/75f78eac-1529-44f7-ae8c-e0d6dd0e9997)

Still seems broken :(

**Comment by aharwood2** [comment]
OK thanks Ian. Not really sure what to do here so will bump it until I have more time to look into it.

**Comment by aharwood2** [comment]
I will get round to firing up CapX in Docker / VS for Mac on my Macbook in the next week or two and then see if I can look into and test a fix for this.

**Comment by aharwood2** [comment]
I need to update my Mac since I don't have the required version of Safari so I'll set that running now and will have a look at this over Xmas probably.
