### ISSUE TITLE
Import old timesheet data

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#576]
We will need to import all the old timesheet data for our team into CapX from an Innate export report. This can be done with a DB migration.

**Comment by aharwood2** [comment]
Issues I can see with this:

### Granularity
We only have data summed up by week so we cannot add accurate timesheets with daily entries. One solution would be to simply average out the values over 5 days. Although it is wrong, and even more wrong for weeks with closure days, and even worse for people who are on FWAs I don't think it matters as we don't ever look at daily values for any automated reporting.

### Codes / Tasks
When reading in the records, we should remove any code in the DB that doesn't have a task as it is essentially unusable. Before we do though, we need to check to see whether the code the timesheet references is in the DB and if not add it. If it is then there, is there a task that matches, if not add it. Renaming shouldn't be a problem as long as nothing is renamed after the final export.

**Comment by ianhinder** [comment]
> We only have data summed up by week

The Innate reports can be set to "day" granularity. Are you using such a report, or something else, to do the export?

**Comment by aharwood2** [comment]
Sure but the system crashes if it has to export too much data (presumably it runs out of memory). This happens when I go from week to day as I'm essentially asking it for 7x more data. Setting it all up again to try to find its limit just takes time I don't have so given the timescales I was just accepting the limitation. I'm out tonight so I don't really have the time to mess with it before it needs to be good to go.

**Comment by aharwood2** [comment]
It also occurs to me that we shouldn't commit the data files for this migration since they contain everyone's timesheet information including codes for sick leave which ought to be considered part of a sickness record. Will have to commit dummy files and then swap in the live files on the server directly and execute the migration manually with a down-up via EF core.
