### ISSUE TITLE
Timesheet in progress saving

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#583]
Keep empty entries in a Timesheet until it's submitted. RSEs can then add entries each day, but keep the initially populated (not implemented currently) entries from their 'template' to use throughout the week.

**Comment by aharwood2** [comment]
Remind me how it works at the moment? Don't they only get deleted when submitting anywway?

**Comment by PhilBradbury** [comment]
The code seems to suggest that they should, but it removes them when that other button (save timesheet) is pressed. I guess if we implement the "save notes on change" and remove the "save timesheet" button it might resolve it... I'm not entirely sure!

**Comment by aharwood2** [comment]
I suspect it will.
