### ISSUE TITLE
Display WLM category for timesheet tasks more subtly

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#592]
Currently the entire text for the Task chosen is highlighted, but this could cause accessibility/legibility issues. A more subtle way to show the relevant categorisation would be useful (a coloured circle with a tooltip description or similar, for example).

**Comment by aharwood2** [comment]
Weren't satisfied with the solution with the foreground and background colours then? :) If it was a component, we could do the show tooltip approach rather than using title.
