### ISSUE TITLE
Using the ordering functionality on the Add Timesheet datagrid causes a crash

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#600]
Clicking the order icon in the Innate Code or Task column crashes the page

**Comment by PhilBradbury** [comment]
![Image](https://github.com/user-attachments/assets/92ed3f41-6dc0-4d64-8625-fed897d6cc5e)

**Comment by PhilBradbury** [comment]
![Image](https://github.com/user-attachments/assets/7d945419-dcd0-4fc4-b2e4-72bc61a78a25)

**Comment by PhilBradbury** [comment]
Easy fix is to just turn off the ability to order the column. Is this the best solution though? I feel like the old system didn't allow you to order them in any way than they were presented, but I couldn't swear to it!

**Comment by aharwood2** [comment]
Initially I thought of #572 but as we use a component, I'm wondering whether if we use components we can fix this?

**Comment by aharwood2** [comment]
I've tried with implementing IComparable on the component but this didn't work. I think there will be a way to do this but it probably has to be done as part of the LoadData method. I have done something like this already on the people grid to allow sorting of the skills so it is possible. Maybe will just disable this for now.
