### ISSUE TITLE
Hours totals not updating after cancelling a row edit on timesheets

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#608]
Reported by @hidonkey2018. Repro as follows:
1. Add new timesheet
2. Add new row
3. Edit values in rows - hours totals update
4. Cancel row add - hours remain with totals despite there being no rows in the timesheet itself.

Suggested fix is to call `HoursChanged` again on cancelling a row edit once the `entityToInsert` has been reset to null so it isn't counted.

**Comment by PhilBradbury** [comment]
Possibly just needs HoursChanged method call adding to the relevant button click event, as per:

![Image](https://github.com/user-attachments/assets/a1b57d62-f9e4-4aa0-af60-61645ddf5f5d)
