### ISSUE TITLE
Template functionality for persisting entries from one timesheet to the next

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#616]
The old system allowed users to 'save' a template of their most often used tasks/activities - this is a useful feature to bring into this system.
- [x] Add a template table with Person Id and the InnateTaskId in the model
- [x] Add migration to create template items from their last timesheet
- [x] Adjust new timesheet method so it adds blank entries into the DB for the new timesheet on its creation
- [x] Remove newly disabled tasks from template
- [x] On submit template entries are updated in the DB - done in a way that doesn't remove zero-entry timesheet rows from the template

**Comment by PhilBradbury** [comment]
1. Base/Default set of entries to add to a first-time user's timesheet
2. Deleted rows in a timesheet are removed from the user's template
3. Newly added rows are added to the template
4. Empty rows on a submitted timesheet are not stored in the database, they do not need to be removed prior to submission (as this would remove them from the user's template)

**Comment by rowleya** [comment]
In some ways, if it just copied last weeks categories without the hours, it would likely be the most useful, since that would then reflect the point when people change from one thing to another.   I guess for some people copying the hours could help, but could also encourage mis-reporting!

**Comment by PhilBradbury** [comment]
It won't transfer the hours forward, just the categories... apologies if that wasn't very clear. 🙂

**Comment by rowleya** [comment]
I had assumed that was the intention, just when writing the above I wondered if copying hours was a useful feature, but then thought probably not a good idea!  I just recorded that thought in case someone else had it too...

**Comment by gcapes** [comment]
I'm afraid this doesn't look to be working reliably.

I've just submitted a timesheet with 5 or 6 categories and was going to submit another one for Xmas hols next week, but I've only got 2 categories ("06 -  All IT - general meetings", and "S-RES014 - Research IT Development and Wellbeing") showing in next week's time sheet even though the one for this week that I just submitted had 6. It's not obvious why there are only these two categories (I think "S-RES014" was a new category in the last timesheet, but not "006 -  All IT - general meetings").

**Comment by rowleya** [comment]
I think you may be falling in to the same trap I did (apologies if not!).  The feature adds to the "template" when you *add* a row specifically (and deletes from the template when you delete a row).  So submitting a sheet is not enough to add to the template; it will only add entries when you do your next sheet and add things then.

**Comment by PhilBradbury** [comment]
If the timesheet was set up prior to the fix being rolled out then it wouldn't take into account the rows you had already added in there in it. If this wasn't the case then it looks like ther's an issue. 

If you add/remove rows to this new one you've created and then try creating a new one after that to see if the new additions are rolled forward... and please let me know if it still fails (hopefully it won't!). :)

**Comment by gcapes** [comment]
Ok, I'll try that. But first, it seems that the freeze in #670 means it's submitted an empty time sheet and I can't figure out how to edit the submitted time sheet. The only "action" is to view it.

**Comment by PhilBradbury** [comment]
How odd. It shouldn't be submitting it unless you click the actual submit button - at that point it's non-editible (to you) and will have to be rejected by your Line Manager for you to be able to change it again.

**Comment by aharwood2** [comment]
Closed by #673
