### ISSUE TITLE
Timesheet: Sorting on Total after Clicking Add Removes Row but leaves Add Disabled

### ISSUE THREAD

**Issue by lasse-cs** [UoMResearchIT/CapX#621]
I'm able to get into a state where the option to add a row is disabled, but I am not currently adding a row. Forcing me to reload the page.

### Steps to Reproduce:
- Select a timesheet to Edit
- Click +Add to add a new row 
![image](https://github.com/user-attachments/assets/1d1054c9-8e39-449f-a2ea-051dc4797a0d)

- The +Add button is now disabled as a new row is being added
![image](https://github.com/user-attachments/assets/3781d383-0db5-4ad2-a7f3-21e7360d6919)

- Do NOT add any data to the row
- Press on the header of the TOTAL column to trigger sorting
- The data row disappears, but the +Add button does not re-enable
![image](https://github.com/user-attachments/assets/c78c8724-c22d-4f0f-a4ce-2caa61627782)

**Comment by PhilBradbury** [comment]
Interesting, I thought we'd turned off the sorting as it causes all sorts of problems trying to keep track of what's in each row.

Thanks for reporting it, this scenario has never been part of my testing! 🙂

**Comment by aharwood2** [comment]
I think we turned sorting off on certain columns. Can easily be turned off for the whole grid though as the grid itself has a sortable property. Don't think people will missing sorting?

**Comment by PhilBradbury** [comment]
Yep, sorting shouldn't be enabled for the grid. This should fix the issue.
