### ISSUE TITLE
Disappearing timesheet categories/ save on enter request

### ISSUE THREAD

**Issue by gcapes** [UoMResearchIT/CapX#622]
It's a bit clunky that you have to save before changing category, otherwise you lose your data. This is when adding a new category. If it could save on hitting enter or clicking away, that would be great - this seems to happen for previously saved categories. In this scenario, the lost category doesn't show when you search for it again - you have to reload the page for it to be searchable again.

**Comment by aharwood2** [comment]
If I understand this correctly there might be two things here?

1. A feature request where you would like to be able to hit enter to leave edit mode for the row and save the row, mimicking the green tick button (and presumably escape to mimic the discard button?) -- covered by #623. 
2. An actual bug where if you choose a code from the drop down but cancel the edit with no hours, it stays permanently removed from the drop down source.

Do I have that right?

**Comment by gcapes** [comment]
Yep, that's right.

**Comment by aharwood2** [comment]
I'm not sure I'm able to reproduce this. Am I doing this correctly?
https://github.com/user-attachments/assets/8607d126-1fee-4d86-b19a-9ad542f17349

**Comment by aharwood2** [comment]
I'm going to merge a PR related to this issue assuming that it somehow fixed it. If it hasn't then please do re-open!

**Comment by gcapes** [comment]
I guess you're doing it "correctly", and I'm not, but this is what I was doing to give rise to the error
[cinnamon-2024-12-12T125901+0000.webm](https://github.com/user-attachments/assets/bd6c9da8-0dea-4474-91fe-86a1672b012f)

You'll see that the "processes and administration" subtask is missing the second time round. 
So what I was trying to do was:
after adding time in "processes and admin" (assuming it was saved even though I'd not clicked the save button), I then wanted to add another time entry to "grafmarine", but in doing so, it removed by (apparently unsaved) entries from the processes category, which then isn't searchable without a reload of the page.

**Comment by aharwood2** [comment]
Got it -- yes, this is a workflow we hadn't thought of. Will re-open this now as it needs looking at.

**Comment by aharwood2** [comment]
In the short-term, I'll just disable the buttons so you have to save the row you are editing before trying to edit another. I know it is more of a workaround but I think that when we look at #623 there might be a more general change to the UI required which will catch this sort of thing and maybe make the issue moot.
