### ISSUE TITLE
Show weekends and non-working days in different colour

### ISSUE THREAD

**Issue by SJaffa** [UoMResearchIT/CapX#626]
When entering data it is easy to loose what column you are looking at and enter Wednesday's work on Thursday's column. Highlighting the weekends and/or other non-working days in a different background colour would make this easier.

**Comment by PhilBradbury** [comment]
Colour coding columns in the grid is surprisingly tricky! I've had a brief look into this as I was thinking that alternating the shading vertically (as it does horizontally) would be helpful. I'll investigate it further.

**Comment by aharwood2** [comment]
We can also set the `AllowVirtualization` property to true of the grid itself and that would make the rows scroll leaving the header in place?

**Comment by PhilBradbury** [comment]
This would probably need to be done via some cellrender method call. Look at the header text of the column to see if it needs to have the background colour set (mon/weds/fri/sat/sun) and set it accordingly.
