### ISSUE TITLE
Allow future changes to an RSE's FTE availability

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#63]
If an RSE changes from full time to part time (for instance), or becomes a manager after being full-time technical, then at a certain date their FTE availability on CapX would need to change.

I'd like to be able to put this in CapX as either a separate person record, or preferably another 'availability' record attached to the same person. This is so we can still record their current availability for existing projects.

This needs either an end date to their current person record (which is probably a good idea anyway, so we can show if someone is leaving the team), after which we can no longer book time for them to avoid confusion, or a smarter system that looks at future availability of the same person and can tell if someone is overallocated if they are still booked as 100% FTE when they've reduced their hours.

Tasks:
- [x] Add new table to hold Availabilty entity with Start Date, End Date and Value properties.
- [x] Set one-to-many relationship with a Person entity and add migration.
- [x] Update the colouring on the capacity charts to use the new model.
- [x] Add an Availability add/edit/delete component within the add/edit person page.
- [x] Add the service layer to existing PersonService or create a new service.

**Comment by aharwood2** [comment]
This is a good one actually and something we need to do for Scott. The easy way would be to create a new person record for them at a different FTE but that is clumsy. To do it properly we would have to do what you suggest but then scheduling could get fun. Probably a big-ish job but really needs to be done by Feb 23.

**Comment by aharwood2** [comment]
OK I've had a think about how we might go about this and updated the tasks. Not a quick task but definitely doable. Will need to be done before #70 as that will depend on our data model.

**Comment by aharwood2** [comment]
This is now all done. Works quite well actually. The changes in FTE are recorded against a particular person and the capacity colouring responds to these changes as well as the capacity query. When I do the next upgrade, I will need to remember to take Scott Archer-Nicholls 2 and merge him back into the original Scott Archer-Nicholls! :)
