### ISSUE TITLE
Feedback when timesheets are saved

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#647]
Moaving away from the Notes field shows a message saying the timesheet has been updated, this would be helpful for providing feedback when rows are added/updated

**Comment by PhilBradbury** [comment]
![Image](https://github.com/user-attachments/assets/0dab0508-7ff1-4749-8207-6cb020b83fbd)

**Comment by aharwood2** [comment]
Was done as part of #616.
