### ISSUE TITLE
Check before submission of timesheet

### ISSUE THREAD

**Issue by Scottan** [UoMResearchIT/CapX#648]
First time I did my timesheet, I tried to save after doing the first day and accidentally submitted, then did the next week as if it was this week, so my line manager had to reject two timesheets before I could fix!

I was used to there being a save button in the bottom left. I get that this isn't necessary, but having a confirmation pop-up before submitting would have saved a lot of time (especially if it doesn't yet add up to full hours).

**Comment by aharwood2** [comment]
I think the best thing to do here is to just add a popup before actioning the submit. Easy fix!
