### ISSUE TITLE
Insert a new task into existing task list

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#65]
New task is added to the bottom of the task list. Can I insert a new task to the middle? 
In African Cities project they got a bit of extra work and funding, that should be put before maintenance, but at the moment it appears as the last one.

**Comment by aharwood2** [comment]
I think we can probably sort this out by simply having the tasks order themselves based on start date rather than the date they were created. Should be an easy fix.

**Comment by aharwood2** [comment]
Changed to order by date so they are sorted correctly.
