### ISSUE TITLE
Allow Line Managers to see staff competencies

### ISSUE THREAD

**Issue by rowleya** [UoMResearchIT/CapX#650]
As a line manager, I would like to be able to view the competencies assesments of my staff (though actually was a request from a staff member whether I would be able to view this for the PDR etc.).

As CapX now knows who is who's LM, this might now be possible.

**Comment by aharwood2** [comment]
Indeed it is and I snuck it into #642 although completely accept that is was bad practice to not raise an issue and link it. #DoAsISayNotAsIDo 😄
