### ISSUE TITLE
Data dashboard looking further ahead

### ISSUE THREAD

**Issue by SJaffa** [UoMResearchIT/CapX#652]
Could the charts in the data dashboard be extended to look further ahead? Requests come in for work up to 5 years in the future, it would be nice to see how our availability (confirmed and unconfirmed) scales over that time.

**Comment by aharwood2** [comment]
You can do this by setting the "years ahead" value at the top of the page. Can you try that and see if it does what you want?

**Comment by SJaffa** [comment]
Aha yes that button is exactly what I wanted, I hadn't noticed those settings at all! Thanks!
