### ISSUE TITLE
Add additional funding to an existing project

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#66]
An existing project now gets a bit of extra funding, do I just add this to the agreed budget?

**Comment by aharwood2** [comment]
I guess this needs to be documented as to how we do this. In priniciple, yes we can just increase the budget recorded on the edit project page. We should probably add a new task to record the second phase too? I'll flag to update the Readme with instructions on how to handle this.

**Comment by aharwood2** [comment]
Updated the README for v1.3
