### ISSUE TITLE
Inclusion of email addresses in Note leads to error about failed @mention

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#667]
When I include an email address in a Note, I get an error about the @mention not being able to be parsed correctly when I save the Note.

Is there a way to escape it, or should CapX just assume that if it can't parse an @mention, it is not an @mention? Maybe it should only parse them if the @ is at the start of a word?  i.e. @wibble would lead to an error, but john@wibble would not?

Not super urgent, of course :)

**Comment by aharwood2** [comment]
I guess we just need to make the parsing logic smarter 😄

**Comment by aharwood2** [comment]
This is a couple of issues still with this:
1. The popup is not armed without a space meaning that typing at at the start of a note does not fire the popup.
2. Using backspace up to a space and then inserting an at symbol does not show the popup.
