### ISSUE TITLE
Unallocated RSEs not appearing in capacity planner

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#69]
At present any RSE who has no allocation at all is not appearing in the chart of the capacity planner, making it easy to overlook their availability. Their names are still in the drop-down list, and when selected it shows them as 'no data to display' correctly, however I'd like to see them on the main chart too.

**Comment by aharwood2** [comment]
This is a consequence of the ApexChart library that is used to plot the graphs. I can have a look to see if there is a flag to show empty entries, otherwise I can just do it programmatically I expect or develop a hack of some kind :)

**Comment by aharwood2** [comment]
OK done.
