### ISSUE TITLE
Setup SSL for website

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#71]
Move from Self Certification to the University's "standard" implementation of SSL.

**Comment by aharwood2** [comment]
Thanks Phil.

**Comment by aharwood2** [comment]
I've opened a ticket on Ivanti (#641768) to get an SSL cert from IDAM and added the rse-researchit and my own email address to get the reminders for renewal.

**Comment by aharwood2** [comment]
Got cert back and copied it over so hopefully done.
