### ISSUE TITLE
Adding a task without an Innate code crashes

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#90]
If this field is left blank it just crashes rather than presenting the form error so needs fixing. Workaround is just to re-add the task and add something in the field.

**Comment by ajerrison-manchester** [comment]
Do we need to add an Innate code if the project is just a grant application? If it is not due to start for ages and might not get the funding anyway then it doesn't really need a code. Perhaps this field could be optional? Or only mandatory when the status changes to Active?

**Comment by aharwood2** [comment]
I'm thinking of moving the Innate code back to the project model, have it as a required field but use a Dropdown box with a (sadly static) list of Innate codes I got off John Clifford plus a default "None" option?

**Comment by ajerrison-manchester** [comment]
We could have the Innate activity code on the CapX project and the Innate task code on the CapX task?

**Comment by aharwood2** [comment]
That makes sense however I can't seem to get a list of tasks out of Innate at the moment. I do have a list of the activity codes though so I can at least half-fix this: 
[Active Project List.xlsx](https://github.com/UoMResearchIT/RSE-PPM-Tool/files/11375745/Active.Project.List.xlsx)

**Comment by aharwood2** [comment]
OK I've add an embedded resource for all the activity codes and have removed the task level value. We can easily get the tasks associated with an activity out of innate so I'm leaving this for now although your suggestion makes sense. Changed to a dropdown to read from the embedded resource to save us effort but now we have to maintain that since there is no public API to read the activities from Innate which would have been better. In the next release.
