### ISSUE TITLE
Project: Add in documentation on the three different money fields

### ISSUE THREAD

**Issue by PBarnby** [UoMResearchIT/CapX#91]
The "budget" at project level needs to be the budget agreed with the PI and what is on the request document. 
The total of the sub tasks is how much money we are planning on spending
The actuals is how much money it actually costs us

**Comment by aharwood2** [comment]
I think I need to start using the Wiki and to arrange it by page with definitions etc. on each page.

**Comment by aharwood2** [comment]
Updated documentation in the new wiki.
