### ISSUE TITLE
Projects : Retain selection in portfolio selection

### ISSUE THREAD

**Issue by PBarnby** [UoMResearchIT/CapX#93]
On the projects page, when a selection has been made e.g. MDS, when the page is left to view projects etc, on returning to the page it would be useful to retain that selection rather than seeing all project and making the selection repeatedly

**Comment by aharwood2** [comment]
Duplicate of #58 ?

**Comment by PBarnby** [comment]
> Duplicate of #58 ?

Yes, sorry.

**Comment by aharwood2** [comment]
Closing as duplicate.
