### ISSUE TITLE
Availability results when searching: not taking into account new variable availability functionality 

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#95]
On the capacity screen, when I search for availability over a certain date range, the RSE's availability that is shown in the results only takes into account their 'headline' availability rather than any changes that are current.

So taking Aman as an example: he started as 100% available, but later on his availability for project work was reduced to 80%. However when you search for available RSEs his %FTE available just remains at 100% minus his current allocation.

**Comment by aharwood2** [comment]
I'll have a look into this as on the face of it I can't reproduce it but it could be that it is related to when the availablility change and the query window are relative to each other. It could also be that the percentage shown is a percentage of someone's FTE available i.e. if a person at part-time is avaialble for their full working hours of 0.5 FTE they may show as 100% available. I'll check this one out.

**Comment by aharwood2** [comment]
The extensive rewrite of the query feature I think has caught and fixed this but happy for you to double check in v1.4.
