### ISSUE TITLE
Fixed work and holidays/strike/sickness etc

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#97]
I think this is probably more of a question about process rather than a bug or functionality change:

I've had a couple of fixed work projects run over their allotted time because of unforeseen circumstances such as more annual leave than expected, strike action or assignment to training. Do we either:

1. Create 'before' and 'after' tasks on the project, which take place either side of the holiday? I did this on RTP-52. The problem with this is that the RSE appears to be unallocated during the time they are on holiday. We could reduce an RSE's availability to 0 during annual leave however for fixed duration project annual leave is irrelevant.
2. Simply add the number of holiday/strike days to the end of the fixed work project? I did this on one of the RTP-59 tasks. The problem here is that the number of days for the task in CapX do not then reflect the number of days actually paid for.
3. Create an 'unavailable' project where we 'allocate' RSEs to holiday tasks, strike tasks etc? We could have a training project too.

Possibly option 2 is the least amount of admin work for us, but the least accurate. :-)

**Comment by aharwood2** [comment]
It is an interesting one this. Obviously the 0.84 FTE is supposed to take into account holidays but not strikes and it doesn't apply per project but overall so you are always going to get some projects that are burning slow and others that burn fast. I think we need to think about the point of the system -- it's primary use is to give a reasonably accurate picture of staff availability and to keep track of how much work has actually been done. As long as they are shown as being occupied with no gaps then that is crucial. The odd project overrunning is not the end of the world and if things don't start exactly as the plan shows then that is also not too bad. I usually create an extra task at the end of the agreed task to take into account overrun. The "budget" field on the project states how much they actually paid for whereas the "budget" of each task is driven by what we schedule. They don't have to agree (in fact they definitely won't unless every works like machines!) and I think this is OK. As you say, the issue really is documentation and process as to how we use the tool. It is something to be added to the readme for sure (feel free to add it yourself if you want). I like suggestion two as it is simple and people are still shown as being occupied at the correct rate even if their actuals are behind. Also relates to #91.

**Comment by aharwood2** [comment]
Will update the readme or start to arrange documentation by page / feature in the Wiki instead so it is easier to find the info.

**Comment by aharwood2** [comment]
I've added some documentation to the wiki for this.
